// source: history.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var pokemon_pb = require('./pokemon_pb.js');
goog.object.extend(proto, pokemon_pb);
var enums_pb = require('./enums_pb.js');
goog.object.extend(proto, enums_pb);
var messages_pb = require('./messages_pb.js');
goog.object.extend(proto, messages_pb);
goog.exportSymbol('proto.history.ActionTypeEnum', null, global);
goog.exportSymbol('proto.history.Boost', null, global);
goog.exportSymbol('proto.history.HistorySide', null, global);
goog.exportSymbol('proto.history.HistoryStep', null, global);
goog.exportSymbol('proto.history.HyphenArg', null, global);
goog.exportSymbol('proto.history.PseudoWeather', null, global);
goog.exportSymbol('proto.history.Sidecondition', null, global);
goog.exportSymbol('proto.history.Volatilestatus', null, global);
goog.exportSymbol('proto.history.Weather', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.history.Boost = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.history.Boost, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.history.Boost.displayName = 'proto.history.Boost';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.history.Sidecondition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.history.Sidecondition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.history.Sidecondition.displayName = 'proto.history.Sidecondition';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.history.Volatilestatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.history.Volatilestatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.history.Volatilestatus.displayName = 'proto.history.Volatilestatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.history.HyphenArg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.history.HyphenArg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.history.HyphenArg.displayName = 'proto.history.HyphenArg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.history.HistorySide = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.history.HistorySide.repeatedFields_, null);
};
goog.inherits(proto.history.HistorySide, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.history.HistorySide.displayName = 'proto.history.HistorySide';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.history.Weather = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.history.Weather, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.history.Weather.displayName = 'proto.history.Weather';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.history.PseudoWeather = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.history.PseudoWeather, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.history.PseudoWeather.displayName = 'proto.history.PseudoWeather';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.history.HistoryStep = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.history.HistoryStep, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.history.HistoryStep.displayName = 'proto.history.HistoryStep';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.history.Boost.prototype.toObject = function(opt_includeInstance) {
  return proto.history.Boost.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.history.Boost} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.Boost.toObject = function(includeInstance, msg) {
  var f, obj = {
    index: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.history.Boost}
 */
proto.history.Boost.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.history.Boost;
  return proto.history.Boost.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.history.Boost} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.history.Boost}
 */
proto.history.Boost.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enums.BoostsEnum} */ (reader.readEnum());
      msg.setIndex(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.history.Boost.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.history.Boost.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.history.Boost} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.Boost.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIndex();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional enums.BoostsEnum index = 1;
 * @return {!proto.enums.BoostsEnum}
 */
proto.history.Boost.prototype.getIndex = function() {
  return /** @type {!proto.enums.BoostsEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.enums.BoostsEnum} value
 * @return {!proto.history.Boost} returns this
 */
proto.history.Boost.prototype.setIndex = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 value = 2;
 * @return {number}
 */
proto.history.Boost.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.history.Boost} returns this
 */
proto.history.Boost.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.history.Sidecondition.prototype.toObject = function(opt_includeInstance) {
  return proto.history.Sidecondition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.history.Sidecondition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.Sidecondition.toObject = function(includeInstance, msg) {
  var f, obj = {
    index: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.history.Sidecondition}
 */
proto.history.Sidecondition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.history.Sidecondition;
  return proto.history.Sidecondition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.history.Sidecondition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.history.Sidecondition}
 */
proto.history.Sidecondition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enums.SideconditionsEnum} */ (reader.readEnum());
      msg.setIndex(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.history.Sidecondition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.history.Sidecondition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.history.Sidecondition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.Sidecondition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIndex();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional enums.SideconditionsEnum index = 1;
 * @return {!proto.enums.SideconditionsEnum}
 */
proto.history.Sidecondition.prototype.getIndex = function() {
  return /** @type {!proto.enums.SideconditionsEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.enums.SideconditionsEnum} value
 * @return {!proto.history.Sidecondition} returns this
 */
proto.history.Sidecondition.prototype.setIndex = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 value = 2;
 * @return {number}
 */
proto.history.Sidecondition.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.history.Sidecondition} returns this
 */
proto.history.Sidecondition.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.history.Volatilestatus.prototype.toObject = function(opt_includeInstance) {
  return proto.history.Volatilestatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.history.Volatilestatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.Volatilestatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    index: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.history.Volatilestatus}
 */
proto.history.Volatilestatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.history.Volatilestatus;
  return proto.history.Volatilestatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.history.Volatilestatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.history.Volatilestatus}
 */
proto.history.Volatilestatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enums.VolatilestatusEnum} */ (reader.readEnum());
      msg.setIndex(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.history.Volatilestatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.history.Volatilestatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.history.Volatilestatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.Volatilestatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIndex();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional enums.VolatilestatusEnum index = 1;
 * @return {!proto.enums.VolatilestatusEnum}
 */
proto.history.Volatilestatus.prototype.getIndex = function() {
  return /** @type {!proto.enums.VolatilestatusEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.enums.VolatilestatusEnum} value
 * @return {!proto.history.Volatilestatus} returns this
 */
proto.history.Volatilestatus.prototype.setIndex = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 value = 2;
 * @return {number}
 */
proto.history.Volatilestatus.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.history.Volatilestatus} returns this
 */
proto.history.Volatilestatus.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.history.HyphenArg.prototype.toObject = function(opt_includeInstance) {
  return proto.history.HyphenArg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.history.HyphenArg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.HyphenArg.toObject = function(includeInstance, msg) {
  var f, obj = {
    index: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.history.HyphenArg}
 */
proto.history.HyphenArg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.history.HyphenArg;
  return proto.history.HyphenArg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.history.HyphenArg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.history.HyphenArg}
 */
proto.history.HyphenArg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enums.HyphenargsEnum} */ (reader.readEnum());
      msg.setIndex(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.history.HyphenArg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.history.HyphenArg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.history.HyphenArg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.HyphenArg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIndex();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional enums.HyphenargsEnum index = 1;
 * @return {!proto.enums.HyphenargsEnum}
 */
proto.history.HyphenArg.prototype.getIndex = function() {
  return /** @type {!proto.enums.HyphenargsEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.enums.HyphenargsEnum} value
 * @return {!proto.history.HyphenArg} returns this
 */
proto.history.HyphenArg.prototype.setIndex = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool value = 2;
 * @return {boolean}
 */
proto.history.HyphenArg.prototype.getValue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.history.HyphenArg} returns this
 */
proto.history.HyphenArg.prototype.setValue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.history.HistorySide.repeatedFields_ = [2,3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.history.HistorySide.prototype.toObject = function(opt_includeInstance) {
  return proto.history.HistorySide.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.history.HistorySide} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.HistorySide.toObject = function(includeInstance, msg) {
  var f, obj = {
    active: (f = msg.getActive()) && pokemon_pb.Pokemon.toObject(includeInstance, f),
    boostsList: jspb.Message.toObjectList(msg.getBoostsList(),
    proto.history.Boost.toObject, includeInstance),
    sideconditionsList: jspb.Message.toObjectList(msg.getSideconditionsList(),
    proto.history.Sidecondition.toObject, includeInstance),
    volatilestatusList: jspb.Message.toObjectList(msg.getVolatilestatusList(),
    proto.history.Volatilestatus.toObject, includeInstance),
    hyphenargsList: jspb.Message.toObjectList(msg.getHyphenargsList(),
    proto.history.HyphenArg.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.history.HistorySide}
 */
proto.history.HistorySide.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.history.HistorySide;
  return proto.history.HistorySide.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.history.HistorySide} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.history.HistorySide}
 */
proto.history.HistorySide.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new pokemon_pb.Pokemon;
      reader.readMessage(value,pokemon_pb.Pokemon.deserializeBinaryFromReader);
      msg.setActive(value);
      break;
    case 2:
      var value = new proto.history.Boost;
      reader.readMessage(value,proto.history.Boost.deserializeBinaryFromReader);
      msg.addBoosts(value);
      break;
    case 3:
      var value = new proto.history.Sidecondition;
      reader.readMessage(value,proto.history.Sidecondition.deserializeBinaryFromReader);
      msg.addSideconditions(value);
      break;
    case 4:
      var value = new proto.history.Volatilestatus;
      reader.readMessage(value,proto.history.Volatilestatus.deserializeBinaryFromReader);
      msg.addVolatilestatus(value);
      break;
    case 5:
      var value = new proto.history.HyphenArg;
      reader.readMessage(value,proto.history.HyphenArg.deserializeBinaryFromReader);
      msg.addHyphenargs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.history.HistorySide.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.history.HistorySide.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.history.HistorySide} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.HistorySide.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActive();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      pokemon_pb.Pokemon.serializeBinaryToWriter
    );
  }
  f = message.getBoostsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.history.Boost.serializeBinaryToWriter
    );
  }
  f = message.getSideconditionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.history.Sidecondition.serializeBinaryToWriter
    );
  }
  f = message.getVolatilestatusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.history.Volatilestatus.serializeBinaryToWriter
    );
  }
  f = message.getHyphenargsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.history.HyphenArg.serializeBinaryToWriter
    );
  }
};


/**
 * optional pokemon.Pokemon active = 1;
 * @return {?proto.pokemon.Pokemon}
 */
proto.history.HistorySide.prototype.getActive = function() {
  return /** @type{?proto.pokemon.Pokemon} */ (
    jspb.Message.getWrapperField(this, pokemon_pb.Pokemon, 1));
};


/**
 * @param {?proto.pokemon.Pokemon|undefined} value
 * @return {!proto.history.HistorySide} returns this
*/
proto.history.HistorySide.prototype.setActive = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.history.HistorySide} returns this
 */
proto.history.HistorySide.prototype.clearActive = function() {
  return this.setActive(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.history.HistorySide.prototype.hasActive = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Boost boosts = 2;
 * @return {!Array<!proto.history.Boost>}
 */
proto.history.HistorySide.prototype.getBoostsList = function() {
  return /** @type{!Array<!proto.history.Boost>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.history.Boost, 2));
};


/**
 * @param {!Array<!proto.history.Boost>} value
 * @return {!proto.history.HistorySide} returns this
*/
proto.history.HistorySide.prototype.setBoostsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.history.Boost=} opt_value
 * @param {number=} opt_index
 * @return {!proto.history.Boost}
 */
proto.history.HistorySide.prototype.addBoosts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.history.Boost, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.history.HistorySide} returns this
 */
proto.history.HistorySide.prototype.clearBoostsList = function() {
  return this.setBoostsList([]);
};


/**
 * repeated Sidecondition sideConditions = 3;
 * @return {!Array<!proto.history.Sidecondition>}
 */
proto.history.HistorySide.prototype.getSideconditionsList = function() {
  return /** @type{!Array<!proto.history.Sidecondition>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.history.Sidecondition, 3));
};


/**
 * @param {!Array<!proto.history.Sidecondition>} value
 * @return {!proto.history.HistorySide} returns this
*/
proto.history.HistorySide.prototype.setSideconditionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.history.Sidecondition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.history.Sidecondition}
 */
proto.history.HistorySide.prototype.addSideconditions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.history.Sidecondition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.history.HistorySide} returns this
 */
proto.history.HistorySide.prototype.clearSideconditionsList = function() {
  return this.setSideconditionsList([]);
};


/**
 * repeated Volatilestatus volatileStatus = 4;
 * @return {!Array<!proto.history.Volatilestatus>}
 */
proto.history.HistorySide.prototype.getVolatilestatusList = function() {
  return /** @type{!Array<!proto.history.Volatilestatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.history.Volatilestatus, 4));
};


/**
 * @param {!Array<!proto.history.Volatilestatus>} value
 * @return {!proto.history.HistorySide} returns this
*/
proto.history.HistorySide.prototype.setVolatilestatusList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.history.Volatilestatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.history.Volatilestatus}
 */
proto.history.HistorySide.prototype.addVolatilestatus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.history.Volatilestatus, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.history.HistorySide} returns this
 */
proto.history.HistorySide.prototype.clearVolatilestatusList = function() {
  return this.setVolatilestatusList([]);
};


/**
 * repeated HyphenArg hyphenArgs = 5;
 * @return {!Array<!proto.history.HyphenArg>}
 */
proto.history.HistorySide.prototype.getHyphenargsList = function() {
  return /** @type{!Array<!proto.history.HyphenArg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.history.HyphenArg, 5));
};


/**
 * @param {!Array<!proto.history.HyphenArg>} value
 * @return {!proto.history.HistorySide} returns this
*/
proto.history.HistorySide.prototype.setHyphenargsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.history.HyphenArg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.history.HyphenArg}
 */
proto.history.HistorySide.prototype.addHyphenargs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.history.HyphenArg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.history.HistorySide} returns this
 */
proto.history.HistorySide.prototype.clearHyphenargsList = function() {
  return this.setHyphenargsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.history.Weather.prototype.toObject = function(opt_includeInstance) {
  return proto.history.Weather.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.history.Weather} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.Weather.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.history.Weather}
 */
proto.history.Weather.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.history.Weather;
  return proto.history.Weather.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.history.Weather} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.history.Weather}
 */
proto.history.Weather.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enums.WeathersEnum} */ (reader.readEnum());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.history.Weather.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.history.Weather.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.history.Weather} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.Weather.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional enums.WeathersEnum value = 1;
 * @return {!proto.enums.WeathersEnum}
 */
proto.history.Weather.prototype.getValue = function() {
  return /** @type {!proto.enums.WeathersEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.enums.WeathersEnum} value
 * @return {!proto.history.Weather} returns this
 */
proto.history.Weather.prototype.setValue = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.history.PseudoWeather.prototype.toObject = function(opt_includeInstance) {
  return proto.history.PseudoWeather.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.history.PseudoWeather} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.PseudoWeather.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: (f = msg.getValue()) && messages_pb.PseudoweatherMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.history.PseudoWeather}
 */
proto.history.PseudoWeather.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.history.PseudoWeather;
  return proto.history.PseudoWeather.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.history.PseudoWeather} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.history.PseudoWeather}
 */
proto.history.PseudoWeather.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new messages_pb.PseudoweatherMessage;
      reader.readMessage(value,messages_pb.PseudoweatherMessage.deserializeBinaryFromReader);
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.history.PseudoWeather.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.history.PseudoWeather.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.history.PseudoWeather} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.PseudoWeather.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      messages_pb.PseudoweatherMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional messages.PseudoweatherMessage value = 1;
 * @return {?proto.messages.PseudoweatherMessage}
 */
proto.history.PseudoWeather.prototype.getValue = function() {
  return /** @type{?proto.messages.PseudoweatherMessage} */ (
    jspb.Message.getWrapperField(this, messages_pb.PseudoweatherMessage, 1));
};


/**
 * @param {?proto.messages.PseudoweatherMessage|undefined} value
 * @return {!proto.history.PseudoWeather} returns this
*/
proto.history.PseudoWeather.prototype.setValue = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.history.PseudoWeather} returns this
 */
proto.history.PseudoWeather.prototype.clearValue = function() {
  return this.setValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.history.PseudoWeather.prototype.hasValue = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.history.HistoryStep.prototype.toObject = function(opt_includeInstance) {
  return proto.history.HistoryStep.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.history.HistoryStep} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.HistoryStep.toObject = function(includeInstance, msg) {
  var f, obj = {
    p1: (f = msg.getP1()) && proto.history.HistorySide.toObject(includeInstance, f),
    p2: (f = msg.getP2()) && proto.history.HistorySide.toObject(includeInstance, f),
    weather: (f = msg.getWeather()) && proto.history.Weather.toObject(includeInstance, f),
    pseudoweather: (f = msg.getPseudoweather()) && proto.history.PseudoWeather.toObject(includeInstance, f),
    action: jspb.Message.getFieldWithDefault(msg, 5, 0),
    move: jspb.Message.getFieldWithDefault(msg, 6, 0),
    ismyturn: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    movecounter: jspb.Message.getFieldWithDefault(msg, 8, 0),
    switchcounter: jspb.Message.getFieldWithDefault(msg, 9, 0),
    turn: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.history.HistoryStep}
 */
proto.history.HistoryStep.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.history.HistoryStep;
  return proto.history.HistoryStep.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.history.HistoryStep} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.history.HistoryStep}
 */
proto.history.HistoryStep.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.history.HistorySide;
      reader.readMessage(value,proto.history.HistorySide.deserializeBinaryFromReader);
      msg.setP1(value);
      break;
    case 2:
      var value = new proto.history.HistorySide;
      reader.readMessage(value,proto.history.HistorySide.deserializeBinaryFromReader);
      msg.setP2(value);
      break;
    case 3:
      var value = new proto.history.Weather;
      reader.readMessage(value,proto.history.Weather.deserializeBinaryFromReader);
      msg.setWeather(value);
      break;
    case 4:
      var value = new proto.history.PseudoWeather;
      reader.readMessage(value,proto.history.PseudoWeather.deserializeBinaryFromReader);
      msg.setPseudoweather(value);
      break;
    case 5:
      var value = /** @type {!proto.history.ActionTypeEnum} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 6:
      var value = /** @type {!proto.enums.MovesEnum} */ (reader.readEnum());
      msg.setMove(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsmyturn(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMovecounter(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSwitchcounter(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTurn(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.history.HistoryStep.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.history.HistoryStep.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.history.HistoryStep} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.history.HistoryStep.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getP1();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.history.HistorySide.serializeBinaryToWriter
    );
  }
  f = message.getP2();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.history.HistorySide.serializeBinaryToWriter
    );
  }
  f = message.getWeather();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.history.Weather.serializeBinaryToWriter
    );
  }
  f = message.getPseudoweather();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.history.PseudoWeather.serializeBinaryToWriter
    );
  }
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getMove();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getIsmyturn();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getMovecounter();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getSwitchcounter();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getTurn();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
};


/**
 * optional HistorySide p1 = 1;
 * @return {?proto.history.HistorySide}
 */
proto.history.HistoryStep.prototype.getP1 = function() {
  return /** @type{?proto.history.HistorySide} */ (
    jspb.Message.getWrapperField(this, proto.history.HistorySide, 1));
};


/**
 * @param {?proto.history.HistorySide|undefined} value
 * @return {!proto.history.HistoryStep} returns this
*/
proto.history.HistoryStep.prototype.setP1 = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.clearP1 = function() {
  return this.setP1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.history.HistoryStep.prototype.hasP1 = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional HistorySide p2 = 2;
 * @return {?proto.history.HistorySide}
 */
proto.history.HistoryStep.prototype.getP2 = function() {
  return /** @type{?proto.history.HistorySide} */ (
    jspb.Message.getWrapperField(this, proto.history.HistorySide, 2));
};


/**
 * @param {?proto.history.HistorySide|undefined} value
 * @return {!proto.history.HistoryStep} returns this
*/
proto.history.HistoryStep.prototype.setP2 = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.clearP2 = function() {
  return this.setP2(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.history.HistoryStep.prototype.hasP2 = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Weather weather = 3;
 * @return {?proto.history.Weather}
 */
proto.history.HistoryStep.prototype.getWeather = function() {
  return /** @type{?proto.history.Weather} */ (
    jspb.Message.getWrapperField(this, proto.history.Weather, 3));
};


/**
 * @param {?proto.history.Weather|undefined} value
 * @return {!proto.history.HistoryStep} returns this
*/
proto.history.HistoryStep.prototype.setWeather = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.clearWeather = function() {
  return this.setWeather(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.history.HistoryStep.prototype.hasWeather = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PseudoWeather pseudoweather = 4;
 * @return {?proto.history.PseudoWeather}
 */
proto.history.HistoryStep.prototype.getPseudoweather = function() {
  return /** @type{?proto.history.PseudoWeather} */ (
    jspb.Message.getWrapperField(this, proto.history.PseudoWeather, 4));
};


/**
 * @param {?proto.history.PseudoWeather|undefined} value
 * @return {!proto.history.HistoryStep} returns this
*/
proto.history.HistoryStep.prototype.setPseudoweather = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.clearPseudoweather = function() {
  return this.setPseudoweather(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.history.HistoryStep.prototype.hasPseudoweather = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ActionTypeEnum action = 5;
 * @return {!proto.history.ActionTypeEnum}
 */
proto.history.HistoryStep.prototype.getAction = function() {
  return /** @type {!proto.history.ActionTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.history.ActionTypeEnum} value
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.setAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional enums.MovesEnum move = 6;
 * @return {!proto.enums.MovesEnum}
 */
proto.history.HistoryStep.prototype.getMove = function() {
  return /** @type {!proto.enums.MovesEnum} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.enums.MovesEnum} value
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.setMove = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional bool isMyTurn = 7;
 * @return {boolean}
 */
proto.history.HistoryStep.prototype.getIsmyturn = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.setIsmyturn = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional int32 moveCounter = 8;
 * @return {number}
 */
proto.history.HistoryStep.prototype.getMovecounter = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.setMovecounter = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 switchCounter = 9;
 * @return {number}
 */
proto.history.HistoryStep.prototype.getSwitchcounter = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.setSwitchcounter = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 turn = 10;
 * @return {number}
 */
proto.history.HistoryStep.prototype.getTurn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.history.HistoryStep} returns this
 */
proto.history.HistoryStep.prototype.setTurn = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * @enum {number}
 */
proto.history.ActionTypeEnum = {
  MOVE: 0,
  SWITCH: 1
};

goog.object.extend(exports, proto.history);
