// source: pokemon.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var enums_pb = require('./enums_pb.js');
goog.object.extend(proto, enums_pb);
goog.exportSymbol('proto.pokemon.Move', null, global);
goog.exportSymbol('proto.pokemon.Pokemon', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pokemon.Move = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pokemon.Move, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pokemon.Move.displayName = 'proto.pokemon.Move';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pokemon.Pokemon = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pokemon.Pokemon.repeatedFields_, null);
};
goog.inherits(proto.pokemon.Pokemon, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pokemon.Pokemon.displayName = 'proto.pokemon.Pokemon';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pokemon.Move.prototype.toObject = function(opt_includeInstance) {
  return proto.pokemon.Move.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pokemon.Move} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pokemon.Move.toObject = function(includeInstance, msg) {
  var f, obj = {
    moveid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    ppused: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pokemon.Move}
 */
proto.pokemon.Move.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pokemon.Move;
  return proto.pokemon.Move.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pokemon.Move} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pokemon.Move}
 */
proto.pokemon.Move.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enums.MovesEnum} */ (reader.readEnum());
      msg.setMoveid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPpused(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pokemon.Move.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pokemon.Move.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pokemon.Move} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pokemon.Move.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMoveid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getPpused();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional enums.MovesEnum moveId = 1;
 * @return {!proto.enums.MovesEnum}
 */
proto.pokemon.Move.prototype.getMoveid = function() {
  return /** @type {!proto.enums.MovesEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.enums.MovesEnum} value
 * @return {!proto.pokemon.Move} returns this
 */
proto.pokemon.Move.prototype.setMoveid = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 ppUsed = 2;
 * @return {number}
 */
proto.pokemon.Move.prototype.getPpused = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.pokemon.Move} returns this
 */
proto.pokemon.Move.prototype.setPpused = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pokemon.Pokemon.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pokemon.Pokemon.prototype.toObject = function(opt_includeInstance) {
  return proto.pokemon.Pokemon.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pokemon.Pokemon} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pokemon.Pokemon.toObject = function(includeInstance, msg) {
  var f, obj = {
    species: jspb.Message.getFieldWithDefault(msg, 1, 0),
    item: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ability: jspb.Message.getFieldWithDefault(msg, 3, 0),
    movesetList: jspb.Message.toObjectList(msg.getMovesetList(),
    proto.pokemon.Move.toObject, includeInstance),
    hpratio: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    active: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    fainted: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    level: jspb.Message.getFieldWithDefault(msg, 8, 0),
    gender: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pokemon.Pokemon}
 */
proto.pokemon.Pokemon.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pokemon.Pokemon;
  return proto.pokemon.Pokemon.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pokemon.Pokemon} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pokemon.Pokemon}
 */
proto.pokemon.Pokemon.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enums.SpeciesEnum} */ (reader.readEnum());
      msg.setSpecies(value);
      break;
    case 2:
      var value = /** @type {!proto.enums.ItemsEnum} */ (reader.readEnum());
      msg.setItem(value);
      break;
    case 3:
      var value = /** @type {!proto.enums.AbilitiesEnum} */ (reader.readEnum());
      msg.setAbility(value);
      break;
    case 4:
      var value = new proto.pokemon.Move;
      reader.readMessage(value,proto.pokemon.Move.deserializeBinaryFromReader);
      msg.addMoveset(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHpratio(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setActive(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFainted(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLevel(value);
      break;
    case 9:
      var value = /** @type {!proto.enums.GendersEnum} */ (reader.readEnum());
      msg.setGender(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pokemon.Pokemon.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pokemon.Pokemon.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pokemon.Pokemon} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pokemon.Pokemon.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpecies();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getItem();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getAbility();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getMovesetList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.pokemon.Move.serializeBinaryToWriter
    );
  }
  f = message.getHpratio();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getActive();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getFainted();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getGender();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional enums.SpeciesEnum species = 1;
 * @return {!proto.enums.SpeciesEnum}
 */
proto.pokemon.Pokemon.prototype.getSpecies = function() {
  return /** @type {!proto.enums.SpeciesEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.enums.SpeciesEnum} value
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.setSpecies = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional enums.ItemsEnum item = 2;
 * @return {!proto.enums.ItemsEnum}
 */
proto.pokemon.Pokemon.prototype.getItem = function() {
  return /** @type {!proto.enums.ItemsEnum} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.enums.ItemsEnum} value
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.setItem = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional enums.AbilitiesEnum ability = 3;
 * @return {!proto.enums.AbilitiesEnum}
 */
proto.pokemon.Pokemon.prototype.getAbility = function() {
  return /** @type {!proto.enums.AbilitiesEnum} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.enums.AbilitiesEnum} value
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.setAbility = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * repeated Move moveset = 4;
 * @return {!Array<!proto.pokemon.Move>}
 */
proto.pokemon.Pokemon.prototype.getMovesetList = function() {
  return /** @type{!Array<!proto.pokemon.Move>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pokemon.Move, 4));
};


/**
 * @param {!Array<!proto.pokemon.Move>} value
 * @return {!proto.pokemon.Pokemon} returns this
*/
proto.pokemon.Pokemon.prototype.setMovesetList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.pokemon.Move=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pokemon.Move}
 */
proto.pokemon.Pokemon.prototype.addMoveset = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.pokemon.Move, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.clearMovesetList = function() {
  return this.setMovesetList([]);
};


/**
 * optional float hpRatio = 5;
 * @return {number}
 */
proto.pokemon.Pokemon.prototype.getHpratio = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.setHpratio = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional bool active = 6;
 * @return {boolean}
 */
proto.pokemon.Pokemon.prototype.getActive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.setActive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool fainted = 7;
 * @return {boolean}
 */
proto.pokemon.Pokemon.prototype.getFainted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.setFainted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional int32 level = 8;
 * @return {number}
 */
proto.pokemon.Pokemon.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional enums.GendersEnum gender = 9;
 * @return {!proto.enums.GendersEnum}
 */
proto.pokemon.Pokemon.prototype.getGender = function() {
  return /** @type {!proto.enums.GendersEnum} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.enums.GendersEnum} value
 * @return {!proto.pokemon.Pokemon} returns this
 */
proto.pokemon.Pokemon.prototype.setGender = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


goog.object.extend(exports, proto.pokemon);
