from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class EntityPublicNodeFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ENTITY_PUBLIC_NODE_FEATURE___UNSPECIFIED: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__ITEM_EFFECT: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__GENDER: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__ACTIVE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__FAINTED: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__HP: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__MAXHP: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__HP_RATIO: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__STATUS: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__TOXIC_TURNS: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__SLEEP_TURNS: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__BEING_CALLED_BACK: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__TRAPPED: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__NEWLY_SWITCHED: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__LEVEL: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__HAS_STATUS: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__BOOST_ATK_VALUE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__BOOST_DEF_VALUE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPA_VALUE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPD_VALUE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPE_VALUE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__BOOST_ACCURACY_VALUE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__BOOST_EVASION_VALUE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES0: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES1: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES2: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES3: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES4: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES5: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES6: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES7: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__VOLATILES8: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__SIDE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__TYPECHANGE0: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__TYPECHANGE1: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__NUM_MOVES: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__LAST_MOVE: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__MEGA: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__PRIMAL: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__MOVEPP0: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__MOVEPP1: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__MOVEPP2: _ClassVar[EntityPublicNodeFeature]
    ENTITY_PUBLIC_NODE_FEATURE__MOVEPP3: _ClassVar[EntityPublicNodeFeature]

class EntityRevealedNodeFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ENTITY_REVEALED_NODE_FEATURE___UNSPECIFIED: _ClassVar[EntityRevealedNodeFeature]
    ENTITY_REVEALED_NODE_FEATURE__SPECIES: _ClassVar[EntityRevealedNodeFeature]
    ENTITY_REVEALED_NODE_FEATURE__ITEM: _ClassVar[EntityRevealedNodeFeature]
    ENTITY_REVEALED_NODE_FEATURE__ABILITY: _ClassVar[EntityRevealedNodeFeature]
    ENTITY_REVEALED_NODE_FEATURE__MOVEID0: _ClassVar[EntityRevealedNodeFeature]
    ENTITY_REVEALED_NODE_FEATURE__MOVEID1: _ClassVar[EntityRevealedNodeFeature]
    ENTITY_REVEALED_NODE_FEATURE__MOVEID2: _ClassVar[EntityRevealedNodeFeature]
    ENTITY_REVEALED_NODE_FEATURE__MOVEID3: _ClassVar[EntityRevealedNodeFeature]
    ENTITY_REVEALED_NODE_FEATURE__TERA_TYPE: _ClassVar[EntityRevealedNodeFeature]

class EntityPrivateNodeFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ENTITY_PRIVATE_NODE_FEATURE___UNSPECIFIED: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__SPECIES: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__ITEM: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__ABILITY: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__MOVEID0: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__MOVEID1: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__MOVEID2: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__MOVEID3: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__EV_HP: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__EV_ATK: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__EV_DEF: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__EV_SPA: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__EV_SPD: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__EV_SPE: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__IV_HP: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__IV_ATK: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__IV_DEF: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__IV_SPA: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__IV_SPD: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__IV_SPE: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__NATURE: _ClassVar[EntityPrivateNodeFeature]
    ENTITY_PRIVATE_NODE_FEATURE__TERA_TYPE: _ClassVar[EntityPrivateNodeFeature]

class MovesetHasPP(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MOVESET_HAS_PP___UNSPECIFIED: _ClassVar[MovesetHasPP]
    MOVESET_HAS_PP__YES: _ClassVar[MovesetHasPP]
    MOVESET_HAS_PP__NO: _ClassVar[MovesetHasPP]

class MovesetFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MOVESET_FEATURE___UNSPECIFIED: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__PP_RATIO: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__MOVE_ID: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__PP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__MAXPP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__HAS_PP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__ACTION_TYPE: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__ENTITY_IDX: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__DISABLED: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__IS_WILDCARD: _ClassVar[MovesetFeature]

class EntityEdgeFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ENTITY_EDGE_FEATURE___UNSPECIFIED: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MAJOR_ARG: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MINOR_ARG0: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MINOR_ARG1: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MINOR_ARG2: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MINOR_ARG3: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__ITEM_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__ABILITY_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__NUM_FROM_TYPES: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN0: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN1: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN2: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN3: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN4: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__NUM_FROM_SOURCES: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN0: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN1: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN2: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN3: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN4: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__DAMAGE_RATIO: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__HEAL_RATIO: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__EFFECT_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_ATK_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_DEF_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_SPA_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_SPD_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_SPE_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_ACCURACY_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_EVASION_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__STATUS_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MOVE_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__HIT_COUNT: _ClassVar[EntityEdgeFeature]

class FieldFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    FIELD_FEATURE___UNSPECIFIED: _ClassVar[FieldFeature]
    FIELD_FEATURE__WEATHER_ID: _ClassVar[FieldFeature]
    FIELD_FEATURE__WEATHER_MIN_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__WEATHER_MAX_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__TERRAIN_ID: _ClassVar[FieldFeature]
    FIELD_FEATURE__TERRAIN_MIN_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__TERRAIN_MAX_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__PSEUDOWEATHER_ID: _ClassVar[FieldFeature]
    FIELD_FEATURE__PSEUDOWEATHER_MIN_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__PSEUDOWEATHER_MAX_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__MY_SIDECONDITIONS0: _ClassVar[FieldFeature]
    FIELD_FEATURE__MY_SIDECONDITIONS1: _ClassVar[FieldFeature]
    FIELD_FEATURE__MY_TOXIC_SPIKES: _ClassVar[FieldFeature]
    FIELD_FEATURE__MY_SPIKES: _ClassVar[FieldFeature]
    FIELD_FEATURE__OPP_SIDECONDITIONS0: _ClassVar[FieldFeature]
    FIELD_FEATURE__OPP_SIDECONDITIONS1: _ClassVar[FieldFeature]
    FIELD_FEATURE__OPP_TOXIC_SPIKES: _ClassVar[FieldFeature]
    FIELD_FEATURE__OPP_SPIKES: _ClassVar[FieldFeature]
    FIELD_FEATURE__REQUEST_COUNT: _ClassVar[FieldFeature]
    FIELD_FEATURE__VALID: _ClassVar[FieldFeature]
    FIELD_FEATURE__INDEX: _ClassVar[FieldFeature]
    FIELD_FEATURE__TURN_VALUE: _ClassVar[FieldFeature]
    FIELD_FEATURE__TURN_ORDER_VALUE: _ClassVar[FieldFeature]
    FIELD_FEATURE__TYPE: _ClassVar[FieldFeature]
    FIELD_FEATURE__RELEVANT_ENTITY_IDX0: _ClassVar[FieldFeature]
    FIELD_FEATURE__RELEVANT_ENTITY_IDX1: _ClassVar[FieldFeature]
    FIELD_FEATURE__RELEVANT_ENTITY_IDX2: _ClassVar[FieldFeature]
    FIELD_FEATURE__RELEVANT_ENTITY_IDX3: _ClassVar[FieldFeature]
    FIELD_FEATURE__RELEVANT_ENTITY_IDX4: _ClassVar[FieldFeature]
    FIELD_FEATURE__RELEVANT_ENTITY_IDX5: _ClassVar[FieldFeature]
    FIELD_FEATURE__RELEVANT_ENTITY_IDX6: _ClassVar[FieldFeature]
    FIELD_FEATURE__RELEVANT_ENTITY_IDX7: _ClassVar[FieldFeature]
    FIELD_FEATURE__NUM_RELEVANT: _ClassVar[FieldFeature]

class InfoFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    INFO_FEATURE___UNSPECIFIED: _ClassVar[InfoFeature]
    INFO_FEATURE__DONE: _ClassVar[InfoFeature]
    INFO_FEATURE__PLAYER_INDEX: _ClassVar[InfoFeature]
    INFO_FEATURE__TURN: _ClassVar[InfoFeature]
    INFO_FEATURE__REQUEST_COUNT: _ClassVar[InfoFeature]
    INFO_FEATURE__WIN_REWARD: _ClassVar[InfoFeature]
    INFO_FEATURE__FIB_REWARD: _ClassVar[InfoFeature]
    INFO_FEATURE__MY_FAINTED_COUNT: _ClassVar[InfoFeature]
    INFO_FEATURE__OPP_FAINTED_COUNT: _ClassVar[InfoFeature]
    INFO_FEATURE__MY_HP_COUNT: _ClassVar[InfoFeature]
    INFO_FEATURE__OPP_HP_COUNT: _ClassVar[InfoFeature]
    INFO_FEATURE__NUM_ACTIVE: _ClassVar[InfoFeature]
    INFO_FEATURE__SWITCH_ORDER_VALUE0: _ClassVar[InfoFeature]
    INFO_FEATURE__SWITCH_ORDER_VALUE1: _ClassVar[InfoFeature]
    INFO_FEATURE__SWITCH_ORDER_VALUE2: _ClassVar[InfoFeature]
    INFO_FEATURE__SWITCH_ORDER_VALUE3: _ClassVar[InfoFeature]
    INFO_FEATURE__SWITCH_ORDER_VALUE4: _ClassVar[InfoFeature]
    INFO_FEATURE__SWITCH_ORDER_VALUE5: _ClassVar[InfoFeature]
    INFO_FEATURE__REQUEST_TYPE: _ClassVar[InfoFeature]
    INFO_FEATURE__HAS_PREV_ACTION: _ClassVar[InfoFeature]
    INFO_FEATURE__PREV_ACTION_SRC: _ClassVar[InfoFeature]
    INFO_FEATURE__PREV_ACTION_TGT: _ClassVar[InfoFeature]

class ActionType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ACTION_TYPE___UNSPECIFIED: _ClassVar[ActionType]
    ACTION_TYPE__MOVE: _ClassVar[ActionType]
    ACTION_TYPE__SWITCH: _ClassVar[ActionType]

class RequestType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    REQUEST_TYPE___UNSPECIFIED: _ClassVar[RequestType]
    REQUEST_TYPE__MOVE: _ClassVar[RequestType]
    REQUEST_TYPE__SWITCH: _ClassVar[RequestType]
    REQUEST_TYPE__TEAM: _ClassVar[RequestType]

class PackedSetFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PACKED_SET_FEATURE___UNSPECIFIED: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__SPECIES: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__ITEM: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__ABILITY: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__MOVE1: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__MOVE2: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__MOVE3: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__MOVE4: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__NATURE: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__GENDER: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__HP_EV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__ATK_EV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__DEF_EV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__SPA_EV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__SPD_EV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__SPE_EV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__HP_IV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__ATK_IV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__DEF_IV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__SPA_IV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__SPD_IV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__SPE_IV: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__HIDDENPOWERTYPE: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__TERATYPE: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__LEVEL: _ClassVar[PackedSetFeature]
    PACKED_SET_FEATURE__HAPPINESS: _ClassVar[PackedSetFeature]
ENTITY_PUBLIC_NODE_FEATURE___UNSPECIFIED: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__ITEM_EFFECT: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__GENDER: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__ACTIVE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__FAINTED: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__HP: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__MAXHP: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__HP_RATIO: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__STATUS: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__TOXIC_TURNS: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__SLEEP_TURNS: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__BEING_CALLED_BACK: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__TRAPPED: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__NEWLY_SWITCHED: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__LEVEL: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__HAS_STATUS: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__BOOST_ATK_VALUE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__BOOST_DEF_VALUE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPA_VALUE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPD_VALUE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPE_VALUE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__BOOST_ACCURACY_VALUE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__BOOST_EVASION_VALUE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES0: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES1: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES2: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES3: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES4: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES5: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES6: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES7: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__VOLATILES8: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__SIDE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__TYPECHANGE0: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__TYPECHANGE1: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__NUM_MOVES: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__LAST_MOVE: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__MEGA: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__PRIMAL: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__MOVEPP0: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__MOVEPP1: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__MOVEPP2: EntityPublicNodeFeature
ENTITY_PUBLIC_NODE_FEATURE__MOVEPP3: EntityPublicNodeFeature
ENTITY_REVEALED_NODE_FEATURE___UNSPECIFIED: EntityRevealedNodeFeature
ENTITY_REVEALED_NODE_FEATURE__SPECIES: EntityRevealedNodeFeature
ENTITY_REVEALED_NODE_FEATURE__ITEM: EntityRevealedNodeFeature
ENTITY_REVEALED_NODE_FEATURE__ABILITY: EntityRevealedNodeFeature
ENTITY_REVEALED_NODE_FEATURE__MOVEID0: EntityRevealedNodeFeature
ENTITY_REVEALED_NODE_FEATURE__MOVEID1: EntityRevealedNodeFeature
ENTITY_REVEALED_NODE_FEATURE__MOVEID2: EntityRevealedNodeFeature
ENTITY_REVEALED_NODE_FEATURE__MOVEID3: EntityRevealedNodeFeature
ENTITY_REVEALED_NODE_FEATURE__TERA_TYPE: EntityRevealedNodeFeature
ENTITY_PRIVATE_NODE_FEATURE___UNSPECIFIED: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__SPECIES: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__ITEM: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__ABILITY: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__MOVEID0: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__MOVEID1: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__MOVEID2: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__MOVEID3: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__EV_HP: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__EV_ATK: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__EV_DEF: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__EV_SPA: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__EV_SPD: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__EV_SPE: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__IV_HP: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__IV_ATK: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__IV_DEF: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__IV_SPA: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__IV_SPD: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__IV_SPE: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__NATURE: EntityPrivateNodeFeature
ENTITY_PRIVATE_NODE_FEATURE__TERA_TYPE: EntityPrivateNodeFeature
MOVESET_HAS_PP___UNSPECIFIED: MovesetHasPP
MOVESET_HAS_PP__YES: MovesetHasPP
MOVESET_HAS_PP__NO: MovesetHasPP
MOVESET_FEATURE___UNSPECIFIED: MovesetFeature
MOVESET_FEATURE__PP_RATIO: MovesetFeature
MOVESET_FEATURE__MOVE_ID: MovesetFeature
MOVESET_FEATURE__PP: MovesetFeature
MOVESET_FEATURE__MAXPP: MovesetFeature
MOVESET_FEATURE__HAS_PP: MovesetFeature
MOVESET_FEATURE__ACTION_TYPE: MovesetFeature
MOVESET_FEATURE__ENTITY_IDX: MovesetFeature
MOVESET_FEATURE__DISABLED: MovesetFeature
MOVESET_FEATURE__IS_WILDCARD: MovesetFeature
ENTITY_EDGE_FEATURE___UNSPECIFIED: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MAJOR_ARG: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MINOR_ARG0: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MINOR_ARG1: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MINOR_ARG2: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MINOR_ARG3: EntityEdgeFeature
ENTITY_EDGE_FEATURE__ITEM_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__ABILITY_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__NUM_FROM_TYPES: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN0: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN1: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN2: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN3: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN4: EntityEdgeFeature
ENTITY_EDGE_FEATURE__NUM_FROM_SOURCES: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN0: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN1: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN2: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN3: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN4: EntityEdgeFeature
ENTITY_EDGE_FEATURE__DAMAGE_RATIO: EntityEdgeFeature
ENTITY_EDGE_FEATURE__HEAL_RATIO: EntityEdgeFeature
ENTITY_EDGE_FEATURE__EFFECT_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_ATK_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_DEF_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_SPA_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_SPD_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_SPE_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_ACCURACY_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_EVASION_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__STATUS_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MOVE_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__HIT_COUNT: EntityEdgeFeature
FIELD_FEATURE___UNSPECIFIED: FieldFeature
FIELD_FEATURE__WEATHER_ID: FieldFeature
FIELD_FEATURE__WEATHER_MIN_DURATION: FieldFeature
FIELD_FEATURE__WEATHER_MAX_DURATION: FieldFeature
FIELD_FEATURE__TERRAIN_ID: FieldFeature
FIELD_FEATURE__TERRAIN_MIN_DURATION: FieldFeature
FIELD_FEATURE__TERRAIN_MAX_DURATION: FieldFeature
FIELD_FEATURE__PSEUDOWEATHER_ID: FieldFeature
FIELD_FEATURE__PSEUDOWEATHER_MIN_DURATION: FieldFeature
FIELD_FEATURE__PSEUDOWEATHER_MAX_DURATION: FieldFeature
FIELD_FEATURE__MY_SIDECONDITIONS0: FieldFeature
FIELD_FEATURE__MY_SIDECONDITIONS1: FieldFeature
FIELD_FEATURE__MY_TOXIC_SPIKES: FieldFeature
FIELD_FEATURE__MY_SPIKES: FieldFeature
FIELD_FEATURE__OPP_SIDECONDITIONS0: FieldFeature
FIELD_FEATURE__OPP_SIDECONDITIONS1: FieldFeature
FIELD_FEATURE__OPP_TOXIC_SPIKES: FieldFeature
FIELD_FEATURE__OPP_SPIKES: FieldFeature
FIELD_FEATURE__REQUEST_COUNT: FieldFeature
FIELD_FEATURE__VALID: FieldFeature
FIELD_FEATURE__INDEX: FieldFeature
FIELD_FEATURE__TURN_VALUE: FieldFeature
FIELD_FEATURE__TURN_ORDER_VALUE: FieldFeature
FIELD_FEATURE__TYPE: FieldFeature
FIELD_FEATURE__RELEVANT_ENTITY_IDX0: FieldFeature
FIELD_FEATURE__RELEVANT_ENTITY_IDX1: FieldFeature
FIELD_FEATURE__RELEVANT_ENTITY_IDX2: FieldFeature
FIELD_FEATURE__RELEVANT_ENTITY_IDX3: FieldFeature
FIELD_FEATURE__RELEVANT_ENTITY_IDX4: FieldFeature
FIELD_FEATURE__RELEVANT_ENTITY_IDX5: FieldFeature
FIELD_FEATURE__RELEVANT_ENTITY_IDX6: FieldFeature
FIELD_FEATURE__RELEVANT_ENTITY_IDX7: FieldFeature
FIELD_FEATURE__NUM_RELEVANT: FieldFeature
INFO_FEATURE___UNSPECIFIED: InfoFeature
INFO_FEATURE__DONE: InfoFeature
INFO_FEATURE__PLAYER_INDEX: InfoFeature
INFO_FEATURE__TURN: InfoFeature
INFO_FEATURE__REQUEST_COUNT: InfoFeature
INFO_FEATURE__WIN_REWARD: InfoFeature
INFO_FEATURE__FIB_REWARD: InfoFeature
INFO_FEATURE__MY_FAINTED_COUNT: InfoFeature
INFO_FEATURE__OPP_FAINTED_COUNT: InfoFeature
INFO_FEATURE__MY_HP_COUNT: InfoFeature
INFO_FEATURE__OPP_HP_COUNT: InfoFeature
INFO_FEATURE__NUM_ACTIVE: InfoFeature
INFO_FEATURE__SWITCH_ORDER_VALUE0: InfoFeature
INFO_FEATURE__SWITCH_ORDER_VALUE1: InfoFeature
INFO_FEATURE__SWITCH_ORDER_VALUE2: InfoFeature
INFO_FEATURE__SWITCH_ORDER_VALUE3: InfoFeature
INFO_FEATURE__SWITCH_ORDER_VALUE4: InfoFeature
INFO_FEATURE__SWITCH_ORDER_VALUE5: InfoFeature
INFO_FEATURE__REQUEST_TYPE: InfoFeature
INFO_FEATURE__HAS_PREV_ACTION: InfoFeature
INFO_FEATURE__PREV_ACTION_SRC: InfoFeature
INFO_FEATURE__PREV_ACTION_TGT: InfoFeature
ACTION_TYPE___UNSPECIFIED: ActionType
ACTION_TYPE__MOVE: ActionType
ACTION_TYPE__SWITCH: ActionType
REQUEST_TYPE___UNSPECIFIED: RequestType
REQUEST_TYPE__MOVE: RequestType
REQUEST_TYPE__SWITCH: RequestType
REQUEST_TYPE__TEAM: RequestType
PACKED_SET_FEATURE___UNSPECIFIED: PackedSetFeature
PACKED_SET_FEATURE__SPECIES: PackedSetFeature
PACKED_SET_FEATURE__ITEM: PackedSetFeature
PACKED_SET_FEATURE__ABILITY: PackedSetFeature
PACKED_SET_FEATURE__MOVE1: PackedSetFeature
PACKED_SET_FEATURE__MOVE2: PackedSetFeature
PACKED_SET_FEATURE__MOVE3: PackedSetFeature
PACKED_SET_FEATURE__MOVE4: PackedSetFeature
PACKED_SET_FEATURE__NATURE: PackedSetFeature
PACKED_SET_FEATURE__GENDER: PackedSetFeature
PACKED_SET_FEATURE__HP_EV: PackedSetFeature
PACKED_SET_FEATURE__ATK_EV: PackedSetFeature
PACKED_SET_FEATURE__DEF_EV: PackedSetFeature
PACKED_SET_FEATURE__SPA_EV: PackedSetFeature
PACKED_SET_FEATURE__SPD_EV: PackedSetFeature
PACKED_SET_FEATURE__SPE_EV: PackedSetFeature
PACKED_SET_FEATURE__HP_IV: PackedSetFeature
PACKED_SET_FEATURE__ATK_IV: PackedSetFeature
PACKED_SET_FEATURE__DEF_IV: PackedSetFeature
PACKED_SET_FEATURE__SPA_IV: PackedSetFeature
PACKED_SET_FEATURE__SPD_IV: PackedSetFeature
PACKED_SET_FEATURE__SPE_IV: PackedSetFeature
PACKED_SET_FEATURE__HIDDENPOWERTYPE: PackedSetFeature
PACKED_SET_FEATURE__TERATYPE: PackedSetFeature
PACKED_SET_FEATURE__LEVEL: PackedSetFeature
PACKED_SET_FEATURE__HAPPINESS: PackedSetFeature
