from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class EntityNodeFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ENTITY_NODE_FEATURE___UNSPECIFIED: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__SPECIES: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__ITEM: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__ITEM_EFFECT: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__ABILITY: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__GENDER: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__ACTIVE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__FAINTED: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__HP: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MAXHP: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__HP_RATIO: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__STATUS: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__TOXIC_TURNS: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__SLEEP_TURNS: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__BEING_CALLED_BACK: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__TRAPPED: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__NEWLY_SWITCHED: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__LEVEL: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MOVEID0: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MOVEID1: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MOVEID2: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MOVEID3: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MOVEPP0: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MOVEPP1: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MOVEPP2: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MOVEPP3: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__HAS_STATUS: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__BOOST_ATK_VALUE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__BOOST_DEF_VALUE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__BOOST_SPA_VALUE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__BOOST_SPD_VALUE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__BOOST_SPE_VALUE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__BOOST_ACCURACY_VALUE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__BOOST_EVASION_VALUE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES0: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES1: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES2: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES3: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES4: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES5: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES6: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES7: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__VOLATILES8: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__SIDE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__TYPECHANGE0: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__TYPECHANGE1: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__NUM_MOVES: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__IS_PUBLIC: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__LAST_MOVE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__EV_HP: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__EV_ATK: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__EV_DEF: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__EV_SPA: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__EV_SPD: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__EV_SPE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__IV_HP: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__IV_ATK: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__IV_DEF: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__IV_SPA: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__IV_SPD: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__IV_SPE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__NATURE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__TERA_TYPE: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__MEGA: _ClassVar[EntityNodeFeature]
    ENTITY_NODE_FEATURE__PRIMAL: _ClassVar[EntityNodeFeature]

class MovesetHasPP(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MOVESET_HAS_PP___UNSPECIFIED: _ClassVar[MovesetHasPP]
    MOVESET_HAS_PP__YES: _ClassVar[MovesetHasPP]
    MOVESET_HAS_PP__NO: _ClassVar[MovesetHasPP]

class MovesetFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MOVESET_FEATURE___UNSPECIFIED: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__PP_RATIO: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__MOVE_ID: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__PP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__MAXPP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__HAS_PP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__ACTION_TYPE: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__ENTITY_IDX: _ClassVar[MovesetFeature]

class EntityEdgeFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ENTITY_EDGE_FEATURE___UNSPECIFIED: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MAJOR_ARG: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MINOR_ARG0: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MINOR_ARG1: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MINOR_ARG2: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MINOR_ARG3: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__ITEM_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__ABILITY_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__NUM_FROM_TYPES: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN0: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN1: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN2: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN3: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN4: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__NUM_FROM_SOURCES: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN0: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN1: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN2: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN3: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN4: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__DAMAGE_RATIO: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__HEAL_RATIO: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__EFFECT_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_ATK_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_DEF_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_SPA_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_SPD_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_SPE_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_ACCURACY_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__BOOST_EVASION_VALUE: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__STATUS_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__MOVE_TOKEN: _ClassVar[EntityEdgeFeature]
    ENTITY_EDGE_FEATURE__HIT_COUNT: _ClassVar[EntityEdgeFeature]

class FieldFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    FIELD_FEATURE___UNSPECIFIED: _ClassVar[FieldFeature]
    FIELD_FEATURE__WEATHER_ID: _ClassVar[FieldFeature]
    FIELD_FEATURE__WEATHER_MIN_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__WEATHER_MAX_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__TERRAIN_ID: _ClassVar[FieldFeature]
    FIELD_FEATURE__TERRAIN_MIN_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__TERRAIN_MAX_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__PSEUDOWEATHER_ID: _ClassVar[FieldFeature]
    FIELD_FEATURE__PSEUDOWEATHER_MIN_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__PSEUDOWEATHER_MAX_DURATION: _ClassVar[FieldFeature]
    FIELD_FEATURE__MY_SIDECONDITIONS0: _ClassVar[FieldFeature]
    FIELD_FEATURE__MY_SIDECONDITIONS1: _ClassVar[FieldFeature]
    FIELD_FEATURE__MY_TOXIC_SPIKES: _ClassVar[FieldFeature]
    FIELD_FEATURE__MY_SPIKES: _ClassVar[FieldFeature]
    FIELD_FEATURE__OPP_SIDECONDITIONS0: _ClassVar[FieldFeature]
    FIELD_FEATURE__OPP_SIDECONDITIONS1: _ClassVar[FieldFeature]
    FIELD_FEATURE__OPP_TOXIC_SPIKES: _ClassVar[FieldFeature]
    FIELD_FEATURE__OPP_SPIKES: _ClassVar[FieldFeature]
    FIELD_FEATURE__REQUEST_COUNT: _ClassVar[FieldFeature]
    FIELD_FEATURE__VALID: _ClassVar[FieldFeature]
    FIELD_FEATURE__INDEX: _ClassVar[FieldFeature]
    FIELD_FEATURE__TURN_VALUE: _ClassVar[FieldFeature]
    FIELD_FEATURE__TURN_ORDER_VALUE: _ClassVar[FieldFeature]
    FIELD_FEATURE__TYPE: _ClassVar[FieldFeature]

class InfoFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    INFO_FEATURE___UNSPECIFIED: _ClassVar[InfoFeature]
    INFO_FEATURE__DONE: _ClassVar[InfoFeature]
    INFO_FEATURE__PLAYER_INDEX: _ClassVar[InfoFeature]
    INFO_FEATURE__TURN: _ClassVar[InfoFeature]
    INFO_FEATURE__WIN_REWARD: _ClassVar[InfoFeature]
    INFO_FEATURE__REQUEST_COUNT: _ClassVar[InfoFeature]

class ActionType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ACTION_TYPE___UNSPECIFIED: _ClassVar[ActionType]
    ACTION_TYPE__MOVE: _ClassVar[ActionType]
    ACTION_TYPE__SWITCH: _ClassVar[ActionType]
    ACTION_TYPE__TEAMPREVIEW: _ClassVar[ActionType]
    ACTION_TYPE__DEFAULT: _ClassVar[ActionType]

class ActionMaskFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ACTION_MASK_FEATURE___UNSPECIFIED: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__CAN_MOVE: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__CAN_SWITCH: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__CAN_TEAMPREVIEW: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__MOVE_SLOT_1: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__MOVE_SLOT_2: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__MOVE_SLOT_3: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__MOVE_SLOT_4: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__SWITCH_SLOT_1: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__SWITCH_SLOT_2: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__SWITCH_SLOT_3: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__SWITCH_SLOT_4: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__SWITCH_SLOT_5: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__SWITCH_SLOT_6: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__CAN_MEGA: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__CAN_ZMOVE: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__CAN_MAX: _ClassVar[ActionMaskFeature]
    ACTION_MASK_FEATURE__CAN_TERA: _ClassVar[ActionMaskFeature]
ENTITY_NODE_FEATURE___UNSPECIFIED: EntityNodeFeature
ENTITY_NODE_FEATURE__SPECIES: EntityNodeFeature
ENTITY_NODE_FEATURE__ITEM: EntityNodeFeature
ENTITY_NODE_FEATURE__ITEM_EFFECT: EntityNodeFeature
ENTITY_NODE_FEATURE__ABILITY: EntityNodeFeature
ENTITY_NODE_FEATURE__GENDER: EntityNodeFeature
ENTITY_NODE_FEATURE__ACTIVE: EntityNodeFeature
ENTITY_NODE_FEATURE__FAINTED: EntityNodeFeature
ENTITY_NODE_FEATURE__HP: EntityNodeFeature
ENTITY_NODE_FEATURE__MAXHP: EntityNodeFeature
ENTITY_NODE_FEATURE__HP_RATIO: EntityNodeFeature
ENTITY_NODE_FEATURE__STATUS: EntityNodeFeature
ENTITY_NODE_FEATURE__TOXIC_TURNS: EntityNodeFeature
ENTITY_NODE_FEATURE__SLEEP_TURNS: EntityNodeFeature
ENTITY_NODE_FEATURE__BEING_CALLED_BACK: EntityNodeFeature
ENTITY_NODE_FEATURE__TRAPPED: EntityNodeFeature
ENTITY_NODE_FEATURE__NEWLY_SWITCHED: EntityNodeFeature
ENTITY_NODE_FEATURE__LEVEL: EntityNodeFeature
ENTITY_NODE_FEATURE__MOVEID0: EntityNodeFeature
ENTITY_NODE_FEATURE__MOVEID1: EntityNodeFeature
ENTITY_NODE_FEATURE__MOVEID2: EntityNodeFeature
ENTITY_NODE_FEATURE__MOVEID3: EntityNodeFeature
ENTITY_NODE_FEATURE__MOVEPP0: EntityNodeFeature
ENTITY_NODE_FEATURE__MOVEPP1: EntityNodeFeature
ENTITY_NODE_FEATURE__MOVEPP2: EntityNodeFeature
ENTITY_NODE_FEATURE__MOVEPP3: EntityNodeFeature
ENTITY_NODE_FEATURE__HAS_STATUS: EntityNodeFeature
ENTITY_NODE_FEATURE__BOOST_ATK_VALUE: EntityNodeFeature
ENTITY_NODE_FEATURE__BOOST_DEF_VALUE: EntityNodeFeature
ENTITY_NODE_FEATURE__BOOST_SPA_VALUE: EntityNodeFeature
ENTITY_NODE_FEATURE__BOOST_SPD_VALUE: EntityNodeFeature
ENTITY_NODE_FEATURE__BOOST_SPE_VALUE: EntityNodeFeature
ENTITY_NODE_FEATURE__BOOST_ACCURACY_VALUE: EntityNodeFeature
ENTITY_NODE_FEATURE__BOOST_EVASION_VALUE: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES0: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES1: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES2: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES3: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES4: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES5: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES6: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES7: EntityNodeFeature
ENTITY_NODE_FEATURE__VOLATILES8: EntityNodeFeature
ENTITY_NODE_FEATURE__SIDE: EntityNodeFeature
ENTITY_NODE_FEATURE__TYPECHANGE0: EntityNodeFeature
ENTITY_NODE_FEATURE__TYPECHANGE1: EntityNodeFeature
ENTITY_NODE_FEATURE__NUM_MOVES: EntityNodeFeature
ENTITY_NODE_FEATURE__IS_PUBLIC: EntityNodeFeature
ENTITY_NODE_FEATURE__LAST_MOVE: EntityNodeFeature
ENTITY_NODE_FEATURE__EV_HP: EntityNodeFeature
ENTITY_NODE_FEATURE__EV_ATK: EntityNodeFeature
ENTITY_NODE_FEATURE__EV_DEF: EntityNodeFeature
ENTITY_NODE_FEATURE__EV_SPA: EntityNodeFeature
ENTITY_NODE_FEATURE__EV_SPD: EntityNodeFeature
ENTITY_NODE_FEATURE__EV_SPE: EntityNodeFeature
ENTITY_NODE_FEATURE__IV_HP: EntityNodeFeature
ENTITY_NODE_FEATURE__IV_ATK: EntityNodeFeature
ENTITY_NODE_FEATURE__IV_DEF: EntityNodeFeature
ENTITY_NODE_FEATURE__IV_SPA: EntityNodeFeature
ENTITY_NODE_FEATURE__IV_SPD: EntityNodeFeature
ENTITY_NODE_FEATURE__IV_SPE: EntityNodeFeature
ENTITY_NODE_FEATURE__NATURE: EntityNodeFeature
ENTITY_NODE_FEATURE__TERA_TYPE: EntityNodeFeature
ENTITY_NODE_FEATURE__MEGA: EntityNodeFeature
ENTITY_NODE_FEATURE__PRIMAL: EntityNodeFeature
MOVESET_HAS_PP___UNSPECIFIED: MovesetHasPP
MOVESET_HAS_PP__YES: MovesetHasPP
MOVESET_HAS_PP__NO: MovesetHasPP
MOVESET_FEATURE___UNSPECIFIED: MovesetFeature
MOVESET_FEATURE__PP_RATIO: MovesetFeature
MOVESET_FEATURE__MOVE_ID: MovesetFeature
MOVESET_FEATURE__PP: MovesetFeature
MOVESET_FEATURE__MAXPP: MovesetFeature
MOVESET_FEATURE__HAS_PP: MovesetFeature
MOVESET_FEATURE__ACTION_TYPE: MovesetFeature
MOVESET_FEATURE__ENTITY_IDX: MovesetFeature
ENTITY_EDGE_FEATURE___UNSPECIFIED: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MAJOR_ARG: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MINOR_ARG0: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MINOR_ARG1: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MINOR_ARG2: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MINOR_ARG3: EntityEdgeFeature
ENTITY_EDGE_FEATURE__ITEM_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__ABILITY_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__NUM_FROM_TYPES: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN0: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN1: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN2: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN3: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN4: EntityEdgeFeature
ENTITY_EDGE_FEATURE__NUM_FROM_SOURCES: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN0: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN1: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN2: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN3: EntityEdgeFeature
ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN4: EntityEdgeFeature
ENTITY_EDGE_FEATURE__DAMAGE_RATIO: EntityEdgeFeature
ENTITY_EDGE_FEATURE__HEAL_RATIO: EntityEdgeFeature
ENTITY_EDGE_FEATURE__EFFECT_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_ATK_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_DEF_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_SPA_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_SPD_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_SPE_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_ACCURACY_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__BOOST_EVASION_VALUE: EntityEdgeFeature
ENTITY_EDGE_FEATURE__STATUS_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__MOVE_TOKEN: EntityEdgeFeature
ENTITY_EDGE_FEATURE__HIT_COUNT: EntityEdgeFeature
FIELD_FEATURE___UNSPECIFIED: FieldFeature
FIELD_FEATURE__WEATHER_ID: FieldFeature
FIELD_FEATURE__WEATHER_MIN_DURATION: FieldFeature
FIELD_FEATURE__WEATHER_MAX_DURATION: FieldFeature
FIELD_FEATURE__TERRAIN_ID: FieldFeature
FIELD_FEATURE__TERRAIN_MIN_DURATION: FieldFeature
FIELD_FEATURE__TERRAIN_MAX_DURATION: FieldFeature
FIELD_FEATURE__PSEUDOWEATHER_ID: FieldFeature
FIELD_FEATURE__PSEUDOWEATHER_MIN_DURATION: FieldFeature
FIELD_FEATURE__PSEUDOWEATHER_MAX_DURATION: FieldFeature
FIELD_FEATURE__MY_SIDECONDITIONS0: FieldFeature
FIELD_FEATURE__MY_SIDECONDITIONS1: FieldFeature
FIELD_FEATURE__MY_TOXIC_SPIKES: FieldFeature
FIELD_FEATURE__MY_SPIKES: FieldFeature
FIELD_FEATURE__OPP_SIDECONDITIONS0: FieldFeature
FIELD_FEATURE__OPP_SIDECONDITIONS1: FieldFeature
FIELD_FEATURE__OPP_TOXIC_SPIKES: FieldFeature
FIELD_FEATURE__OPP_SPIKES: FieldFeature
FIELD_FEATURE__REQUEST_COUNT: FieldFeature
FIELD_FEATURE__VALID: FieldFeature
FIELD_FEATURE__INDEX: FieldFeature
FIELD_FEATURE__TURN_VALUE: FieldFeature
FIELD_FEATURE__TURN_ORDER_VALUE: FieldFeature
FIELD_FEATURE__TYPE: FieldFeature
INFO_FEATURE___UNSPECIFIED: InfoFeature
INFO_FEATURE__DONE: InfoFeature
INFO_FEATURE__PLAYER_INDEX: InfoFeature
INFO_FEATURE__TURN: InfoFeature
INFO_FEATURE__WIN_REWARD: InfoFeature
INFO_FEATURE__REQUEST_COUNT: InfoFeature
ACTION_TYPE___UNSPECIFIED: ActionType
ACTION_TYPE__MOVE: ActionType
ACTION_TYPE__SWITCH: ActionType
ACTION_TYPE__TEAMPREVIEW: ActionType
ACTION_TYPE__DEFAULT: ActionType
ACTION_MASK_FEATURE___UNSPECIFIED: ActionMaskFeature
ACTION_MASK_FEATURE__CAN_MOVE: ActionMaskFeature
ACTION_MASK_FEATURE__CAN_SWITCH: ActionMaskFeature
ACTION_MASK_FEATURE__CAN_TEAMPREVIEW: ActionMaskFeature
ACTION_MASK_FEATURE__MOVE_SLOT_1: ActionMaskFeature
ACTION_MASK_FEATURE__MOVE_SLOT_2: ActionMaskFeature
ACTION_MASK_FEATURE__MOVE_SLOT_3: ActionMaskFeature
ACTION_MASK_FEATURE__MOVE_SLOT_4: ActionMaskFeature
ACTION_MASK_FEATURE__SWITCH_SLOT_1: ActionMaskFeature
ACTION_MASK_FEATURE__SWITCH_SLOT_2: ActionMaskFeature
ACTION_MASK_FEATURE__SWITCH_SLOT_3: ActionMaskFeature
ACTION_MASK_FEATURE__SWITCH_SLOT_4: ActionMaskFeature
ACTION_MASK_FEATURE__SWITCH_SLOT_5: ActionMaskFeature
ACTION_MASK_FEATURE__SWITCH_SLOT_6: ActionMaskFeature
ACTION_MASK_FEATURE__CAN_MEGA: ActionMaskFeature
ACTION_MASK_FEATURE__CAN_ZMOVE: ActionMaskFeature
ACTION_MASK_FEATURE__CAN_MAX: ActionMaskFeature
ACTION_MASK_FEATURE__CAN_TERA: ActionMaskFeature
