// source: features.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.ActionType', null, global);
goog.exportSymbol('proto.EntityEdgeFeature', null, global);
goog.exportSymbol('proto.EntityPrivateNodeFeature', null, global);
goog.exportSymbol('proto.EntityPublicNodeFeature', null, global);
goog.exportSymbol('proto.EntityRevealedNodeFeature', null, global);
goog.exportSymbol('proto.FieldFeature', null, global);
goog.exportSymbol('proto.InfoFeature', null, global);
goog.exportSymbol('proto.MovesetFeature', null, global);
goog.exportSymbol('proto.MovesetHasPP', null, global);
goog.exportSymbol('proto.PackedSetFeature', null, global);
goog.exportSymbol('proto.RequestType', null, global);
/**
 * @enum {number}
 */
proto.EntityPublicNodeFeature = {
  ENTITY_PUBLIC_NODE_FEATURE___UNSPECIFIED: 0,
  ENTITY_PUBLIC_NODE_FEATURE__ITEM_EFFECT: 1,
  ENTITY_PUBLIC_NODE_FEATURE__GENDER: 2,
  ENTITY_PUBLIC_NODE_FEATURE__ACTIVE: 3,
  ENTITY_PUBLIC_NODE_FEATURE__FAINTED: 4,
  ENTITY_PUBLIC_NODE_FEATURE__HP: 5,
  ENTITY_PUBLIC_NODE_FEATURE__MAXHP: 6,
  ENTITY_PUBLIC_NODE_FEATURE__HP_RATIO: 7,
  ENTITY_PUBLIC_NODE_FEATURE__STATUS: 8,
  ENTITY_PUBLIC_NODE_FEATURE__TOXIC_TURNS: 9,
  ENTITY_PUBLIC_NODE_FEATURE__SLEEP_TURNS: 10,
  ENTITY_PUBLIC_NODE_FEATURE__BEING_CALLED_BACK: 11,
  ENTITY_PUBLIC_NODE_FEATURE__TRAPPED: 12,
  ENTITY_PUBLIC_NODE_FEATURE__NEWLY_SWITCHED: 13,
  ENTITY_PUBLIC_NODE_FEATURE__LEVEL: 14,
  ENTITY_PUBLIC_NODE_FEATURE__HAS_STATUS: 15,
  ENTITY_PUBLIC_NODE_FEATURE__BOOST_ATK_VALUE: 16,
  ENTITY_PUBLIC_NODE_FEATURE__BOOST_DEF_VALUE: 17,
  ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPA_VALUE: 18,
  ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPD_VALUE: 19,
  ENTITY_PUBLIC_NODE_FEATURE__BOOST_SPE_VALUE: 20,
  ENTITY_PUBLIC_NODE_FEATURE__BOOST_ACCURACY_VALUE: 21,
  ENTITY_PUBLIC_NODE_FEATURE__BOOST_EVASION_VALUE: 22,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES0: 23,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES1: 24,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES2: 25,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES3: 26,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES4: 27,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES5: 28,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES6: 29,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES7: 30,
  ENTITY_PUBLIC_NODE_FEATURE__VOLATILES8: 31,
  ENTITY_PUBLIC_NODE_FEATURE__SIDE: 32,
  ENTITY_PUBLIC_NODE_FEATURE__TYPECHANGE0: 33,
  ENTITY_PUBLIC_NODE_FEATURE__TYPECHANGE1: 34,
  ENTITY_PUBLIC_NODE_FEATURE__NUM_MOVES: 35,
  ENTITY_PUBLIC_NODE_FEATURE__LAST_MOVE: 36,
  ENTITY_PUBLIC_NODE_FEATURE__MEGA: 37,
  ENTITY_PUBLIC_NODE_FEATURE__PRIMAL: 38,
  ENTITY_PUBLIC_NODE_FEATURE__MOVEPP0: 39,
  ENTITY_PUBLIC_NODE_FEATURE__MOVEPP1: 40,
  ENTITY_PUBLIC_NODE_FEATURE__MOVEPP2: 41,
  ENTITY_PUBLIC_NODE_FEATURE__MOVEPP3: 42
};

/**
 * @enum {number}
 */
proto.EntityRevealedNodeFeature = {
  ENTITY_REVEALED_NODE_FEATURE___UNSPECIFIED: 0,
  ENTITY_REVEALED_NODE_FEATURE__SPECIES: 1,
  ENTITY_REVEALED_NODE_FEATURE__ITEM: 2,
  ENTITY_REVEALED_NODE_FEATURE__ABILITY: 3,
  ENTITY_REVEALED_NODE_FEATURE__MOVEID0: 4,
  ENTITY_REVEALED_NODE_FEATURE__MOVEID1: 5,
  ENTITY_REVEALED_NODE_FEATURE__MOVEID2: 6,
  ENTITY_REVEALED_NODE_FEATURE__MOVEID3: 7,
  ENTITY_REVEALED_NODE_FEATURE__TERA_TYPE: 8
};

/**
 * @enum {number}
 */
proto.EntityPrivateNodeFeature = {
  ENTITY_PRIVATE_NODE_FEATURE___UNSPECIFIED: 0,
  ENTITY_PRIVATE_NODE_FEATURE__SPECIES: 1,
  ENTITY_PRIVATE_NODE_FEATURE__ITEM: 2,
  ENTITY_PRIVATE_NODE_FEATURE__ABILITY: 3,
  ENTITY_PRIVATE_NODE_FEATURE__MOVEID0: 4,
  ENTITY_PRIVATE_NODE_FEATURE__MOVEID1: 5,
  ENTITY_PRIVATE_NODE_FEATURE__MOVEID2: 6,
  ENTITY_PRIVATE_NODE_FEATURE__MOVEID3: 7,
  ENTITY_PRIVATE_NODE_FEATURE__EV_HP: 8,
  ENTITY_PRIVATE_NODE_FEATURE__EV_ATK: 9,
  ENTITY_PRIVATE_NODE_FEATURE__EV_DEF: 10,
  ENTITY_PRIVATE_NODE_FEATURE__EV_SPA: 11,
  ENTITY_PRIVATE_NODE_FEATURE__EV_SPD: 12,
  ENTITY_PRIVATE_NODE_FEATURE__EV_SPE: 13,
  ENTITY_PRIVATE_NODE_FEATURE__IV_HP: 14,
  ENTITY_PRIVATE_NODE_FEATURE__IV_ATK: 15,
  ENTITY_PRIVATE_NODE_FEATURE__IV_DEF: 16,
  ENTITY_PRIVATE_NODE_FEATURE__IV_SPA: 17,
  ENTITY_PRIVATE_NODE_FEATURE__IV_SPD: 18,
  ENTITY_PRIVATE_NODE_FEATURE__IV_SPE: 19,
  ENTITY_PRIVATE_NODE_FEATURE__NATURE: 20,
  ENTITY_PRIVATE_NODE_FEATURE__TERA_TYPE: 21
};

/**
 * @enum {number}
 */
proto.MovesetHasPP = {
  MOVESET_HAS_PP___UNSPECIFIED: 0,
  MOVESET_HAS_PP__YES: 1,
  MOVESET_HAS_PP__NO: 2
};

/**
 * @enum {number}
 */
proto.MovesetFeature = {
  MOVESET_FEATURE___UNSPECIFIED: 0,
  MOVESET_FEATURE__PP_RATIO: 1,
  MOVESET_FEATURE__MOVE_ID: 2,
  MOVESET_FEATURE__PP: 3,
  MOVESET_FEATURE__MAXPP: 4,
  MOVESET_FEATURE__HAS_PP: 5,
  MOVESET_FEATURE__ACTION_TYPE: 6,
  MOVESET_FEATURE__ENTITY_IDX: 7,
  MOVESET_FEATURE__DISABLED: 8,
  MOVESET_FEATURE__IS_WILDCARD: 9
};

/**
 * @enum {number}
 */
proto.EntityEdgeFeature = {
  ENTITY_EDGE_FEATURE___UNSPECIFIED: 0,
  ENTITY_EDGE_FEATURE__MAJOR_ARG: 1,
  ENTITY_EDGE_FEATURE__MINOR_ARG0: 2,
  ENTITY_EDGE_FEATURE__MINOR_ARG1: 3,
  ENTITY_EDGE_FEATURE__MINOR_ARG2: 4,
  ENTITY_EDGE_FEATURE__MINOR_ARG3: 5,
  ENTITY_EDGE_FEATURE__ITEM_TOKEN: 6,
  ENTITY_EDGE_FEATURE__ABILITY_TOKEN: 7,
  ENTITY_EDGE_FEATURE__NUM_FROM_TYPES: 8,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN0: 9,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN1: 10,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN2: 11,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN3: 12,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN4: 13,
  ENTITY_EDGE_FEATURE__NUM_FROM_SOURCES: 14,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN0: 15,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN1: 16,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN2: 17,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN3: 18,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN4: 19,
  ENTITY_EDGE_FEATURE__DAMAGE_RATIO: 20,
  ENTITY_EDGE_FEATURE__HEAL_RATIO: 21,
  ENTITY_EDGE_FEATURE__EFFECT_TOKEN: 22,
  ENTITY_EDGE_FEATURE__BOOST_ATK_VALUE: 23,
  ENTITY_EDGE_FEATURE__BOOST_DEF_VALUE: 24,
  ENTITY_EDGE_FEATURE__BOOST_SPA_VALUE: 25,
  ENTITY_EDGE_FEATURE__BOOST_SPD_VALUE: 26,
  ENTITY_EDGE_FEATURE__BOOST_SPE_VALUE: 27,
  ENTITY_EDGE_FEATURE__BOOST_ACCURACY_VALUE: 28,
  ENTITY_EDGE_FEATURE__BOOST_EVASION_VALUE: 29,
  ENTITY_EDGE_FEATURE__STATUS_TOKEN: 30,
  ENTITY_EDGE_FEATURE__MOVE_TOKEN: 31,
  ENTITY_EDGE_FEATURE__HIT_COUNT: 32
};

/**
 * @enum {number}
 */
proto.FieldFeature = {
  FIELD_FEATURE___UNSPECIFIED: 0,
  FIELD_FEATURE__WEATHER_ID: 1,
  FIELD_FEATURE__WEATHER_MIN_DURATION: 2,
  FIELD_FEATURE__WEATHER_MAX_DURATION: 3,
  FIELD_FEATURE__TERRAIN_ID: 4,
  FIELD_FEATURE__TERRAIN_MIN_DURATION: 5,
  FIELD_FEATURE__TERRAIN_MAX_DURATION: 6,
  FIELD_FEATURE__PSEUDOWEATHER_ID: 7,
  FIELD_FEATURE__PSEUDOWEATHER_MIN_DURATION: 8,
  FIELD_FEATURE__PSEUDOWEATHER_MAX_DURATION: 9,
  FIELD_FEATURE__MY_SIDECONDITIONS0: 10,
  FIELD_FEATURE__MY_SIDECONDITIONS1: 11,
  FIELD_FEATURE__MY_TOXIC_SPIKES: 12,
  FIELD_FEATURE__MY_SPIKES: 13,
  FIELD_FEATURE__OPP_SIDECONDITIONS0: 14,
  FIELD_FEATURE__OPP_SIDECONDITIONS1: 15,
  FIELD_FEATURE__OPP_TOXIC_SPIKES: 16,
  FIELD_FEATURE__OPP_SPIKES: 17,
  FIELD_FEATURE__REQUEST_COUNT: 18,
  FIELD_FEATURE__VALID: 19,
  FIELD_FEATURE__INDEX: 20,
  FIELD_FEATURE__TURN_VALUE: 21,
  FIELD_FEATURE__TURN_ORDER_VALUE: 22,
  FIELD_FEATURE__TYPE: 23,
  FIELD_FEATURE__RELEVANT_ENTITY_IDX0: 24,
  FIELD_FEATURE__RELEVANT_ENTITY_IDX1: 25,
  FIELD_FEATURE__RELEVANT_ENTITY_IDX2: 26,
  FIELD_FEATURE__RELEVANT_ENTITY_IDX3: 27,
  FIELD_FEATURE__RELEVANT_ENTITY_IDX4: 28,
  FIELD_FEATURE__RELEVANT_ENTITY_IDX5: 29,
  FIELD_FEATURE__RELEVANT_ENTITY_IDX6: 30,
  FIELD_FEATURE__RELEVANT_ENTITY_IDX7: 31,
  FIELD_FEATURE__NUM_RELEVANT: 32
};

/**
 * @enum {number}
 */
proto.InfoFeature = {
  INFO_FEATURE___UNSPECIFIED: 0,
  INFO_FEATURE__DONE: 1,
  INFO_FEATURE__PLAYER_INDEX: 2,
  INFO_FEATURE__TURN: 3,
  INFO_FEATURE__REQUEST_COUNT: 4,
  INFO_FEATURE__WIN_REWARD: 5,
  INFO_FEATURE__FIB_REWARD: 6,
  INFO_FEATURE__MY_FAINTED_COUNT: 7,
  INFO_FEATURE__OPP_FAINTED_COUNT: 8,
  INFO_FEATURE__MY_HP_COUNT: 9,
  INFO_FEATURE__OPP_HP_COUNT: 10,
  INFO_FEATURE__NUM_ACTIVE: 11,
  INFO_FEATURE__SWITCH_ORDER_VALUE0: 12,
  INFO_FEATURE__SWITCH_ORDER_VALUE1: 13,
  INFO_FEATURE__SWITCH_ORDER_VALUE2: 14,
  INFO_FEATURE__SWITCH_ORDER_VALUE3: 15,
  INFO_FEATURE__SWITCH_ORDER_VALUE4: 16,
  INFO_FEATURE__SWITCH_ORDER_VALUE5: 17,
  INFO_FEATURE__REQUEST_TYPE: 18,
  INFO_FEATURE__HAS_PREV_ACTION: 19,
  INFO_FEATURE__PREV_ACTION_SRC: 20,
  INFO_FEATURE__PREV_ACTION_TGT: 21
};

/**
 * @enum {number}
 */
proto.ActionType = {
  ACTION_TYPE___UNSPECIFIED: 0,
  ACTION_TYPE__MOVE: 1,
  ACTION_TYPE__SWITCH: 2
};

/**
 * @enum {number}
 */
proto.RequestType = {
  REQUEST_TYPE___UNSPECIFIED: 0,
  REQUEST_TYPE__MOVE: 1,
  REQUEST_TYPE__SWITCH: 2,
  REQUEST_TYPE__TEAM: 3
};

/**
 * @enum {number}
 */
proto.PackedSetFeature = {
  PACKED_SET_FEATURE___UNSPECIFIED: 0,
  PACKED_SET_FEATURE__SPECIES: 1,
  PACKED_SET_FEATURE__ITEM: 2,
  PACKED_SET_FEATURE__ABILITY: 3,
  PACKED_SET_FEATURE__MOVE1: 4,
  PACKED_SET_FEATURE__MOVE2: 5,
  PACKED_SET_FEATURE__MOVE3: 6,
  PACKED_SET_FEATURE__MOVE4: 7,
  PACKED_SET_FEATURE__NATURE: 8,
  PACKED_SET_FEATURE__GENDER: 9,
  PACKED_SET_FEATURE__HP_EV: 10,
  PACKED_SET_FEATURE__ATK_EV: 11,
  PACKED_SET_FEATURE__DEF_EV: 12,
  PACKED_SET_FEATURE__SPA_EV: 13,
  PACKED_SET_FEATURE__SPD_EV: 14,
  PACKED_SET_FEATURE__SPE_EV: 15,
  PACKED_SET_FEATURE__HP_IV: 16,
  PACKED_SET_FEATURE__ATK_IV: 17,
  PACKED_SET_FEATURE__DEF_IV: 18,
  PACKED_SET_FEATURE__SPA_IV: 19,
  PACKED_SET_FEATURE__SPD_IV: 20,
  PACKED_SET_FEATURE__SPE_IV: 21,
  PACKED_SET_FEATURE__HIDDENPOWERTYPE: 22,
  PACKED_SET_FEATURE__TERATYPE: 23,
  PACKED_SET_FEATURE__LEVEL: 24,
  PACKED_SET_FEATURE__HAPPINESS: 25
};

goog.object.extend(exports, proto);
