// source: features.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.EntityEdgeFeature', null, global);
goog.exportSymbol('proto.EntityNodeFeature', null, global);
goog.exportSymbol('proto.FieldFeature', null, global);
goog.exportSymbol('proto.InfoFeature', null, global);
goog.exportSymbol('proto.MovesetActionTypeEnum', null, global);
goog.exportSymbol('proto.MovesetFeature', null, global);
goog.exportSymbol('proto.MovesetHasPPEnum', null, global);
goog.exportSymbol('proto.TeamSetFeature', null, global);
/**
 * @enum {number}
 */
proto.EntityNodeFeature = {
  ENTITY_NODE_FEATURE___UNSPECIFIED: 0,
  ENTITY_NODE_FEATURE__SPECIES: 1,
  ENTITY_NODE_FEATURE__ITEM: 2,
  ENTITY_NODE_FEATURE__ITEM_EFFECT: 3,
  ENTITY_NODE_FEATURE__ABILITY: 4,
  ENTITY_NODE_FEATURE__GENDER: 5,
  ENTITY_NODE_FEATURE__ACTIVE: 6,
  ENTITY_NODE_FEATURE__FAINTED: 7,
  ENTITY_NODE_FEATURE__HP: 8,
  ENTITY_NODE_FEATURE__MAXHP: 9,
  ENTITY_NODE_FEATURE__HP_RATIO: 10,
  ENTITY_NODE_FEATURE__STATUS: 11,
  ENTITY_NODE_FEATURE__TOXIC_TURNS: 12,
  ENTITY_NODE_FEATURE__SLEEP_TURNS: 13,
  ENTITY_NODE_FEATURE__BEING_CALLED_BACK: 14,
  ENTITY_NODE_FEATURE__TRAPPED: 15,
  ENTITY_NODE_FEATURE__NEWLY_SWITCHED: 16,
  ENTITY_NODE_FEATURE__LEVEL: 17,
  ENTITY_NODE_FEATURE__MOVEID0: 18,
  ENTITY_NODE_FEATURE__MOVEID1: 19,
  ENTITY_NODE_FEATURE__MOVEID2: 20,
  ENTITY_NODE_FEATURE__MOVEID3: 21,
  ENTITY_NODE_FEATURE__MOVEPP0: 22,
  ENTITY_NODE_FEATURE__MOVEPP1: 23,
  ENTITY_NODE_FEATURE__MOVEPP2: 24,
  ENTITY_NODE_FEATURE__MOVEPP3: 25,
  ENTITY_NODE_FEATURE__HAS_STATUS: 26,
  ENTITY_NODE_FEATURE__BOOST_ATK_VALUE: 27,
  ENTITY_NODE_FEATURE__BOOST_DEF_VALUE: 28,
  ENTITY_NODE_FEATURE__BOOST_SPA_VALUE: 29,
  ENTITY_NODE_FEATURE__BOOST_SPD_VALUE: 30,
  ENTITY_NODE_FEATURE__BOOST_SPE_VALUE: 31,
  ENTITY_NODE_FEATURE__BOOST_ACCURACY_VALUE: 32,
  ENTITY_NODE_FEATURE__BOOST_EVASION_VALUE: 33,
  ENTITY_NODE_FEATURE__VOLATILES0: 34,
  ENTITY_NODE_FEATURE__VOLATILES1: 35,
  ENTITY_NODE_FEATURE__VOLATILES2: 36,
  ENTITY_NODE_FEATURE__VOLATILES3: 37,
  ENTITY_NODE_FEATURE__VOLATILES4: 38,
  ENTITY_NODE_FEATURE__VOLATILES5: 39,
  ENTITY_NODE_FEATURE__VOLATILES6: 40,
  ENTITY_NODE_FEATURE__VOLATILES7: 41,
  ENTITY_NODE_FEATURE__VOLATILES8: 42,
  ENTITY_NODE_FEATURE__SIDE: 43,
  ENTITY_NODE_FEATURE__TYPECHANGE0: 44,
  ENTITY_NODE_FEATURE__TYPECHANGE1: 45,
  ENTITY_NODE_FEATURE__NUM_MOVES: 46,
  ENTITY_NODE_FEATURE__IS_PUBLIC: 47,
  ENTITY_NODE_FEATURE__LAST_MOVE: 48,
  ENTITY_NODE_FEATURE__EV_HP: 49,
  ENTITY_NODE_FEATURE__EV_ATK: 50,
  ENTITY_NODE_FEATURE__EV_DEF: 51,
  ENTITY_NODE_FEATURE__EV_SPA: 52,
  ENTITY_NODE_FEATURE__EV_SPD: 53,
  ENTITY_NODE_FEATURE__EV_SPE: 54,
  ENTITY_NODE_FEATURE__IV_HP: 55,
  ENTITY_NODE_FEATURE__IV_ATK: 56,
  ENTITY_NODE_FEATURE__IV_DEF: 57,
  ENTITY_NODE_FEATURE__IV_SPA: 58,
  ENTITY_NODE_FEATURE__IV_SPD: 59,
  ENTITY_NODE_FEATURE__IV_SPE: 60,
  ENTITY_NODE_FEATURE__NATURE: 61
};

/**
 * @enum {number}
 */
proto.MovesetActionTypeEnum = {
  MOVESET_ACTION_TYPE_ENUM___UNSPECIFIED: 0,
  MOVESET_ACTION_TYPE_ENUM__MOVE: 1,
  MOVESET_ACTION_TYPE_ENUM__SWITCH: 2
};

/**
 * @enum {number}
 */
proto.MovesetHasPPEnum = {
  MOVESET_HAS_PP_ENUM___UNSPECIFIED: 0,
  MOVESET_HAS_PP_ENUM__YES: 1,
  MOVESET_HAS_PP_ENUM__NO: 2
};

/**
 * @enum {number}
 */
proto.MovesetFeature = {
  MOVESET_FEATURE___UNSPECIFIED: 0,
  MOVESET_FEATURE__PP_RATIO: 1,
  MOVESET_FEATURE__MOVE_ID: 2,
  MOVESET_FEATURE__PP: 3,
  MOVESET_FEATURE__MAXPP: 4,
  MOVESET_FEATURE__HAS_PP: 5,
  MOVESET_FEATURE__ACTION_TYPE: 6,
  MOVESET_FEATURE__ENTITY_IDX: 7
};

/**
 * @enum {number}
 */
proto.EntityEdgeFeature = {
  ENTITY_EDGE_FEATURE___UNSPECIFIED: 0,
  ENTITY_EDGE_FEATURE__MAJOR_ARG: 1,
  ENTITY_EDGE_FEATURE__MINOR_ARG0: 2,
  ENTITY_EDGE_FEATURE__MINOR_ARG1: 3,
  ENTITY_EDGE_FEATURE__MINOR_ARG2: 4,
  ENTITY_EDGE_FEATURE__MINOR_ARG3: 5,
  ENTITY_EDGE_FEATURE__ITEM_TOKEN: 6,
  ENTITY_EDGE_FEATURE__ABILITY_TOKEN: 7,
  ENTITY_EDGE_FEATURE__NUM_FROM_TYPES: 8,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN0: 9,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN1: 10,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN2: 11,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN3: 12,
  ENTITY_EDGE_FEATURE__FROM_TYPE_TOKEN4: 13,
  ENTITY_EDGE_FEATURE__NUM_FROM_SOURCES: 14,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN0: 15,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN1: 16,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN2: 17,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN3: 18,
  ENTITY_EDGE_FEATURE__FROM_SOURCE_TOKEN4: 19,
  ENTITY_EDGE_FEATURE__DAMAGE_RATIO: 20,
  ENTITY_EDGE_FEATURE__HEAL_RATIO: 21,
  ENTITY_EDGE_FEATURE__EFFECT_TOKEN: 22,
  ENTITY_EDGE_FEATURE__BOOST_ATK_VALUE: 23,
  ENTITY_EDGE_FEATURE__BOOST_DEF_VALUE: 24,
  ENTITY_EDGE_FEATURE__BOOST_SPA_VALUE: 25,
  ENTITY_EDGE_FEATURE__BOOST_SPD_VALUE: 26,
  ENTITY_EDGE_FEATURE__BOOST_SPE_VALUE: 27,
  ENTITY_EDGE_FEATURE__BOOST_ACCURACY_VALUE: 28,
  ENTITY_EDGE_FEATURE__BOOST_EVASION_VALUE: 29,
  ENTITY_EDGE_FEATURE__STATUS_TOKEN: 30,
  ENTITY_EDGE_FEATURE__MOVE_TOKEN: 31,
  ENTITY_EDGE_FEATURE__HIT_COUNT: 32
};

/**
 * @enum {number}
 */
proto.FieldFeature = {
  FIELD_FEATURE___UNSPECIFIED: 0,
  FIELD_FEATURE__WEATHER_ID: 1,
  FIELD_FEATURE__WEATHER_MIN_DURATION: 2,
  FIELD_FEATURE__WEATHER_MAX_DURATION: 3,
  FIELD_FEATURE__TERRAIN_ID: 4,
  FIELD_FEATURE__TERRAIN_MIN_DURATION: 5,
  FIELD_FEATURE__TERRAIN_MAX_DURATION: 6,
  FIELD_FEATURE__PSEUDOWEATHER_ID: 7,
  FIELD_FEATURE__PSEUDOWEATHER_MIN_DURATION: 8,
  FIELD_FEATURE__PSEUDOWEATHER_MAX_DURATION: 9,
  FIELD_FEATURE__MY_SIDECONDITIONS0: 10,
  FIELD_FEATURE__MY_SIDECONDITIONS1: 11,
  FIELD_FEATURE__MY_TOXIC_SPIKES: 12,
  FIELD_FEATURE__MY_SPIKES: 13,
  FIELD_FEATURE__OPP_SIDECONDITIONS0: 14,
  FIELD_FEATURE__OPP_SIDECONDITIONS1: 15,
  FIELD_FEATURE__OPP_TOXIC_SPIKES: 16,
  FIELD_FEATURE__OPP_SPIKES: 17,
  FIELD_FEATURE__REQUEST_COUNT: 18,
  FIELD_FEATURE__VALID: 19,
  FIELD_FEATURE__INDEX: 20,
  FIELD_FEATURE__TURN_VALUE: 21,
  FIELD_FEATURE__TURN_ORDER_VALUE: 22,
  FIELD_FEATURE__TYPE: 23
};

/**
 * @enum {number}
 */
proto.InfoFeature = {
  INFO_FEATURE___UNSPECIFIED: 0,
  INFO_FEATURE__DONE: 1,
  INFO_FEATURE__PLAYER_INDEX: 2,
  INFO_FEATURE__TURN: 3,
  INFO_FEATURE__WIN_REWARD: 4,
  INFO_FEATURE__REQUEST_COUNT: 5
};

/**
 * @enum {number}
 */
proto.TeamSetFeature = {
  TEAM_SET_FEATURE___UNSPECIFIED: 0,
  TEAM_SET_FEATURE__SPECIES: 1,
  TEAM_SET_FEATURE__ITEM: 2,
  TEAM_SET_FEATURE__ABILITY: 3,
  TEAM_SET_FEATURE__MOVEID0: 4,
  TEAM_SET_FEATURE__MOVEID1: 5,
  TEAM_SET_FEATURE__MOVEID2: 6,
  TEAM_SET_FEATURE__MOVEID3: 7,
  TEAM_SET_FEATURE__NATURE: 8,
  TEAM_SET_FEATURE__GENDER: 9,
  TEAM_SET_FEATURE__EV_HP: 10,
  TEAM_SET_FEATURE__EV_ATK: 11,
  TEAM_SET_FEATURE__EV_DEF: 12,
  TEAM_SET_FEATURE__EV_SPA: 13,
  TEAM_SET_FEATURE__EV_SPD: 14,
  TEAM_SET_FEATURE__EV_SPE: 15,
  TEAM_SET_FEATURE__IV_HP: 16,
  TEAM_SET_FEATURE__IV_ATK: 17,
  TEAM_SET_FEATURE__IV_DEF: 18,
  TEAM_SET_FEATURE__IV_SPA: 19,
  TEAM_SET_FEATURE__IV_SPD: 20,
  TEAM_SET_FEATURE__IV_SPE: 21,
  TEAM_SET_FEATURE__LEVEL: 22,
  TEAM_SET_FEATURE__HAPPINESS: 23,
  TEAM_SET_FEATURE__HIDDEN_POWER_TYPE: 24,
  TEAM_SET_FEATURE__GIGANTAMAX: 25,
  TEAM_SET_FEATURE__DYNAMAX_LEVEL: 26,
  TEAM_SET_FEATURE__TERA_TYPE: 27
};

goog.object.extend(exports, proto);
