// source: state.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var history_pb = require('./history_pb.js');
goog.object.extend(proto, history_pb);
var enums_pb = require('./enums_pb.js');
goog.object.extend(proto, enums_pb);
goog.exportSymbol('proto.rlenv.Info', null, global);
goog.exportSymbol('proto.rlenv.LegalActions', null, global);
goog.exportSymbol('proto.rlenv.Move', null, global);
goog.exportSymbol('proto.rlenv.State', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rlenv.LegalActions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rlenv.LegalActions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rlenv.LegalActions.displayName = 'proto.rlenv.LegalActions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rlenv.Info = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rlenv.Info, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rlenv.Info.displayName = 'proto.rlenv.Info';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rlenv.Move = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rlenv.Move, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rlenv.Move.displayName = 'proto.rlenv.Move';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rlenv.State = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rlenv.State, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rlenv.State.displayName = 'proto.rlenv.State';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rlenv.LegalActions.prototype.toObject = function(opt_includeInstance) {
  return proto.rlenv.LegalActions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rlenv.LegalActions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rlenv.LegalActions.toObject = function(includeInstance, msg) {
  var f, obj = {
    move1: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    move2: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    move3: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    move4: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    switch1: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    switch2: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    switch3: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    switch4: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    switch5: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    switch6: jspb.Message.getBooleanFieldWithDefault(msg, 10, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rlenv.LegalActions}
 */
proto.rlenv.LegalActions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rlenv.LegalActions;
  return proto.rlenv.LegalActions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rlenv.LegalActions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rlenv.LegalActions}
 */
proto.rlenv.LegalActions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMove1(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMove2(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMove3(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMove4(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSwitch1(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSwitch2(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSwitch3(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSwitch4(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSwitch5(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSwitch6(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rlenv.LegalActions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rlenv.LegalActions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rlenv.LegalActions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rlenv.LegalActions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMove1();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMove2();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getMove3();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getMove4();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getSwitch1();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getSwitch2();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getSwitch3();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getSwitch4();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getSwitch5();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getSwitch6();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
};


/**
 * optional bool move1 = 1;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getMove1 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setMove1 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool move2 = 2;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getMove2 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setMove2 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool move3 = 3;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getMove3 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setMove3 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool move4 = 4;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getMove4 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setMove4 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool switch1 = 5;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getSwitch1 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setSwitch1 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool switch2 = 6;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getSwitch2 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setSwitch2 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool switch3 = 7;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getSwitch3 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setSwitch3 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool switch4 = 8;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getSwitch4 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setSwitch4 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool switch5 = 9;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getSwitch5 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setSwitch5 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool switch6 = 10;
 * @return {boolean}
 */
proto.rlenv.LegalActions.prototype.getSwitch6 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.LegalActions} returns this
 */
proto.rlenv.LegalActions.prototype.setSwitch6 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rlenv.Info.prototype.toObject = function(opt_includeInstance) {
  return proto.rlenv.Info.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rlenv.Info} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rlenv.Info.toObject = function(includeInstance, msg) {
  var f, obj = {
    gameid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    done: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    playeronereward: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    playertworeward: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    playerindex: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    turn: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rlenv.Info}
 */
proto.rlenv.Info.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rlenv.Info;
  return proto.rlenv.Info.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rlenv.Info} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rlenv.Info}
 */
proto.rlenv.Info.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGameid(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDone(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPlayeronereward(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPlayertworeward(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPlayerindex(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTurn(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rlenv.Info.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rlenv.Info.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rlenv.Info} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rlenv.Info.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGameid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getDone();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getPlayeronereward();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getPlayertworeward();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getPlayerindex();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getTurn();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional int32 gameId = 1;
 * @return {number}
 */
proto.rlenv.Info.prototype.getGameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.rlenv.Info} returns this
 */
proto.rlenv.Info.prototype.setGameid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool done = 2;
 * @return {boolean}
 */
proto.rlenv.Info.prototype.getDone = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.Info} returns this
 */
proto.rlenv.Info.prototype.setDone = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional float playerOneReward = 3;
 * @return {number}
 */
proto.rlenv.Info.prototype.getPlayeronereward = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rlenv.Info} returns this
 */
proto.rlenv.Info.prototype.setPlayeronereward = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float playerTwoReward = 4;
 * @return {number}
 */
proto.rlenv.Info.prototype.getPlayertworeward = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rlenv.Info} returns this
 */
proto.rlenv.Info.prototype.setPlayertworeward = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional bool playerIndex = 5;
 * @return {boolean}
 */
proto.rlenv.Info.prototype.getPlayerindex = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rlenv.Info} returns this
 */
proto.rlenv.Info.prototype.setPlayerindex = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional int32 turn = 6;
 * @return {number}
 */
proto.rlenv.Info.prototype.getTurn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.rlenv.Info} returns this
 */
proto.rlenv.Info.prototype.setTurn = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rlenv.Move.prototype.toObject = function(opt_includeInstance) {
  return proto.rlenv.Move.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rlenv.Move} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rlenv.Move.toObject = function(includeInstance, msg) {
  var f, obj = {
    moveid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    pp: jspb.Message.getFieldWithDefault(msg, 2, 0),
    maxpp: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rlenv.Move}
 */
proto.rlenv.Move.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rlenv.Move;
  return proto.rlenv.Move.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rlenv.Move} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rlenv.Move}
 */
proto.rlenv.Move.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.enums.MovesEnum} */ (reader.readEnum());
      msg.setMoveid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPp(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxpp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rlenv.Move.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rlenv.Move.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rlenv.Move} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rlenv.Move.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMoveid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getPp();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMaxpp();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional enums.MovesEnum moveId = 1;
 * @return {!proto.enums.MovesEnum}
 */
proto.rlenv.Move.prototype.getMoveid = function() {
  return /** @type {!proto.enums.MovesEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.enums.MovesEnum} value
 * @return {!proto.rlenv.Move} returns this
 */
proto.rlenv.Move.prototype.setMoveid = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 pp = 2;
 * @return {number}
 */
proto.rlenv.Move.prototype.getPp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.rlenv.Move} returns this
 */
proto.rlenv.Move.prototype.setPp = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 maxpp = 3;
 * @return {number}
 */
proto.rlenv.Move.prototype.getMaxpp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.rlenv.Move} returns this
 */
proto.rlenv.Move.prototype.setMaxpp = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rlenv.State.prototype.toObject = function(opt_includeInstance) {
  return proto.rlenv.State.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rlenv.State} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rlenv.State.toObject = function(includeInstance, msg) {
  var f, obj = {
    info: (f = msg.getInfo()) && proto.rlenv.Info.toObject(includeInstance, f),
    legalactions: (f = msg.getLegalactions()) && proto.rlenv.LegalActions.toObject(includeInstance, f),
    history: (f = msg.getHistory()) && history_pb.History.toObject(includeInstance, f),
    moveset: msg.getMoveset_asB64(),
    team: msg.getTeam_asB64(),
    key: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rlenv.State}
 */
proto.rlenv.State.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rlenv.State;
  return proto.rlenv.State.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rlenv.State} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rlenv.State}
 */
proto.rlenv.State.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rlenv.Info;
      reader.readMessage(value,proto.rlenv.Info.deserializeBinaryFromReader);
      msg.setInfo(value);
      break;
    case 2:
      var value = new proto.rlenv.LegalActions;
      reader.readMessage(value,proto.rlenv.LegalActions.deserializeBinaryFromReader);
      msg.setLegalactions(value);
      break;
    case 3:
      var value = new history_pb.History;
      reader.readMessage(value,history_pb.History.deserializeBinaryFromReader);
      msg.setHistory(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMoveset(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTeam(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rlenv.State.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rlenv.State.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rlenv.State} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rlenv.State.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rlenv.Info.serializeBinaryToWriter
    );
  }
  f = message.getLegalactions();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.rlenv.LegalActions.serializeBinaryToWriter
    );
  }
  f = message.getHistory();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      history_pb.History.serializeBinaryToWriter
    );
  }
  f = message.getMoveset_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getTeam_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional Info info = 1;
 * @return {?proto.rlenv.Info}
 */
proto.rlenv.State.prototype.getInfo = function() {
  return /** @type{?proto.rlenv.Info} */ (
    jspb.Message.getWrapperField(this, proto.rlenv.Info, 1));
};


/**
 * @param {?proto.rlenv.Info|undefined} value
 * @return {!proto.rlenv.State} returns this
*/
proto.rlenv.State.prototype.setInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rlenv.State} returns this
 */
proto.rlenv.State.prototype.clearInfo = function() {
  return this.setInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rlenv.State.prototype.hasInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional LegalActions legalActions = 2;
 * @return {?proto.rlenv.LegalActions}
 */
proto.rlenv.State.prototype.getLegalactions = function() {
  return /** @type{?proto.rlenv.LegalActions} */ (
    jspb.Message.getWrapperField(this, proto.rlenv.LegalActions, 2));
};


/**
 * @param {?proto.rlenv.LegalActions|undefined} value
 * @return {!proto.rlenv.State} returns this
*/
proto.rlenv.State.prototype.setLegalactions = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rlenv.State} returns this
 */
proto.rlenv.State.prototype.clearLegalactions = function() {
  return this.setLegalactions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rlenv.State.prototype.hasLegalactions = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional history.History history = 3;
 * @return {?proto.history.History}
 */
proto.rlenv.State.prototype.getHistory = function() {
  return /** @type{?proto.history.History} */ (
    jspb.Message.getWrapperField(this, history_pb.History, 3));
};


/**
 * @param {?proto.history.History|undefined} value
 * @return {!proto.rlenv.State} returns this
*/
proto.rlenv.State.prototype.setHistory = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rlenv.State} returns this
 */
proto.rlenv.State.prototype.clearHistory = function() {
  return this.setHistory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rlenv.State.prototype.hasHistory = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bytes moveset = 4;
 * @return {!(string|Uint8Array)}
 */
proto.rlenv.State.prototype.getMoveset = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes moveset = 4;
 * This is a type-conversion wrapper around `getMoveset()`
 * @return {string}
 */
proto.rlenv.State.prototype.getMoveset_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMoveset()));
};


/**
 * optional bytes moveset = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMoveset()`
 * @return {!Uint8Array}
 */
proto.rlenv.State.prototype.getMoveset_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMoveset()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.rlenv.State} returns this
 */
proto.rlenv.State.prototype.setMoveset = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional bytes team = 5;
 * @return {!(string|Uint8Array)}
 */
proto.rlenv.State.prototype.getTeam = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes team = 5;
 * This is a type-conversion wrapper around `getTeam()`
 * @return {string}
 */
proto.rlenv.State.prototype.getTeam_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTeam()));
};


/**
 * optional bytes team = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTeam()`
 * @return {!Uint8Array}
 */
proto.rlenv.State.prototype.getTeam_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTeam()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.rlenv.State} returns this
 */
proto.rlenv.State.prototype.setTeam = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional string key = 6;
 * @return {string}
 */
proto.rlenv.State.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.rlenv.State} returns this
 */
proto.rlenv.State.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.rlenv);
