from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class EntityFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ENTITY_FEATURE___UNSPECIFIED: _ClassVar[EntityFeature]
    ENTITY_FEATURE__SPECIES: _ClassVar[EntityFeature]
    ENTITY_FEATURE__ITEM: _ClassVar[EntityFeature]
    ENTITY_FEATURE__ITEM_EFFECT: _ClassVar[EntityFeature]
    ENTITY_FEATURE__ABILITY: _ClassVar[EntityFeature]
    ENTITY_FEATURE__GENDER: _ClassVar[EntityFeature]
    ENTITY_FEATURE__ACTIVE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__FAINTED: _ClassVar[EntityFeature]
    ENTITY_FEATURE__HP: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MAXHP: _ClassVar[EntityFeature]
    ENTITY_FEATURE__HP_RATIO: _ClassVar[EntityFeature]
    ENTITY_FEATURE__STATUS: _ClassVar[EntityFeature]
    ENTITY_FEATURE__TOXIC_TURNS: _ClassVar[EntityFeature]
    ENTITY_FEATURE__SLEEP_TURNS: _ClassVar[EntityFeature]
    ENTITY_FEATURE__BEING_CALLED_BACK: _ClassVar[EntityFeature]
    ENTITY_FEATURE__TRAPPED: _ClassVar[EntityFeature]
    ENTITY_FEATURE__NEWLY_SWITCHED: _ClassVar[EntityFeature]
    ENTITY_FEATURE__LEVEL: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MOVEID0: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MOVEID1: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MOVEID2: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MOVEID3: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MOVEPP0: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MOVEPP1: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MOVEPP2: _ClassVar[EntityFeature]
    ENTITY_FEATURE__MOVEPP3: _ClassVar[EntityFeature]
    ENTITY_FEATURE__HAS_STATUS: _ClassVar[EntityFeature]
    ENTITY_FEATURE__BOOST_ATK_VALUE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__BOOST_DEF_VALUE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__BOOST_SPA_VALUE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__BOOST_SPD_VALUE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__BOOST_SPE_VALUE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__BOOST_ACCURACY_VALUE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__BOOST_EVASION_VALUE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES0: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES1: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES2: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES3: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES4: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES5: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES6: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES7: _ClassVar[EntityFeature]
    ENTITY_FEATURE__VOLATILES8: _ClassVar[EntityFeature]
    ENTITY_FEATURE__SIDE: _ClassVar[EntityFeature]
    ENTITY_FEATURE__TYPECHANGE0: _ClassVar[EntityFeature]
    ENTITY_FEATURE__TYPECHANGE1: _ClassVar[EntityFeature]
    ENTITY_FEATURE__ACTION_ID0: _ClassVar[EntityFeature]
    ENTITY_FEATURE__ACTION_ID1: _ClassVar[EntityFeature]
    ENTITY_FEATURE__ACTION_ID2: _ClassVar[EntityFeature]
    ENTITY_FEATURE__ACTION_ID3: _ClassVar[EntityFeature]
    ENTITY_FEATURE__NUM_MOVES: _ClassVar[EntityFeature]
    ENTITY_FEATURE__IS_PUBLIC: _ClassVar[EntityFeature]
    ENTITY_FEATURE__LAST_MOVE: _ClassVar[EntityFeature]

class MovesetActionTypeEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MOVESET_ACTION_TYPE_ENUM___UNSPECIFIED: _ClassVar[MovesetActionTypeEnum]
    MOVESET_ACTION_TYPE_ENUM__MOVE: _ClassVar[MovesetActionTypeEnum]
    MOVESET_ACTION_TYPE_ENUM__SWITCH: _ClassVar[MovesetActionTypeEnum]

class MovesetHasPPEnum(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MOVESET_HAS_PP_ENUM___UNSPECIFIED: _ClassVar[MovesetHasPPEnum]
    MOVESET_HAS_PP_ENUM__YES: _ClassVar[MovesetHasPPEnum]
    MOVESET_HAS_PP_ENUM__NO: _ClassVar[MovesetHasPPEnum]

class MovesetFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MOVESET_FEATURE___UNSPECIFIED: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__ACTION_ID: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__PP_RATIO: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__MOVE_ID: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__SPECIES_ID: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__PP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__MAXPP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__HAS_PP: _ClassVar[MovesetFeature]
    MOVESET_FEATURE__ACTION_TYPE: _ClassVar[MovesetFeature]

class ActionsFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ACTIONS_FEATURE___UNSPECIFIED: _ClassVar[ActionsFeature]
    ACTIONS_FEATURE__MOVE_ID: _ClassVar[ActionsFeature]
    ACTIONS_FEATURE__ACTION_INDEX: _ClassVar[ActionsFeature]

class RelativeEdgeFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    RELATIVE_EDGE_FEATURE___UNSPECIFIED: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__MAJOR_ARG: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__MINOR_ARG0: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__MINOR_ARG1: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__MINOR_ARG2: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__MINOR_ARG3: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__ACTION_TOKEN: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__ITEM_TOKEN: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__ABILITY_TOKEN: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__NUM_FROM_TYPES: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN0: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN1: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN2: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN3: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN4: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__NUM_FROM_SOURCES: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN0: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN1: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN2: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN3: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN4: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__DAMAGE_RATIO: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__HEAL_RATIO: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__EFFECT_TOKEN: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__BOOST_ATK_VALUE: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__BOOST_DEF_VALUE: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__BOOST_SPA_VALUE: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__BOOST_SPD_VALUE: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__BOOST_SPE_VALUE: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__BOOST_ACCURACY_VALUE: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__BOOST_EVASION_VALUE: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__STATUS_TOKEN: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__SIDECONDITIONS0: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__SIDECONDITIONS1: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__TOXIC_SPIKES: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__SPIKES: _ClassVar[RelativeEdgeFeature]
    RELATIVE_EDGE_FEATURE__MOVE_TOKEN: _ClassVar[RelativeEdgeFeature]

class AbsoluteEdgeFeature(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ABSOLUTE_EDGE_FEATURE___UNSPECIFIED: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__TURN_ORDER_VALUE: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__TYPE_TOKEN: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__WEATHER_ID: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__WEATHER_MIN_DURATION: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__WEATHER_MAX_DURATION: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__TERRAIN_ID: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__TERRAIN_MIN_DURATION: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__TERRAIN_MAX_DURATION: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__PSEUDOWEATHER_ID: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__PSEUDOWEATHER_MIN_DURATION: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__PSEUDOWEATHER_MAX_DURATION: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__REQUEST_COUNT: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__VALID: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__INDEX: _ClassVar[AbsoluteEdgeFeature]
    ABSOLUTE_EDGE_FEATURE__TURN_VALUE: _ClassVar[AbsoluteEdgeFeature]
ENTITY_FEATURE___UNSPECIFIED: EntityFeature
ENTITY_FEATURE__SPECIES: EntityFeature
ENTITY_FEATURE__ITEM: EntityFeature
ENTITY_FEATURE__ITEM_EFFECT: EntityFeature
ENTITY_FEATURE__ABILITY: EntityFeature
ENTITY_FEATURE__GENDER: EntityFeature
ENTITY_FEATURE__ACTIVE: EntityFeature
ENTITY_FEATURE__FAINTED: EntityFeature
ENTITY_FEATURE__HP: EntityFeature
ENTITY_FEATURE__MAXHP: EntityFeature
ENTITY_FEATURE__HP_RATIO: EntityFeature
ENTITY_FEATURE__STATUS: EntityFeature
ENTITY_FEATURE__TOXIC_TURNS: EntityFeature
ENTITY_FEATURE__SLEEP_TURNS: EntityFeature
ENTITY_FEATURE__BEING_CALLED_BACK: EntityFeature
ENTITY_FEATURE__TRAPPED: EntityFeature
ENTITY_FEATURE__NEWLY_SWITCHED: EntityFeature
ENTITY_FEATURE__LEVEL: EntityFeature
ENTITY_FEATURE__MOVEID0: EntityFeature
ENTITY_FEATURE__MOVEID1: EntityFeature
ENTITY_FEATURE__MOVEID2: EntityFeature
ENTITY_FEATURE__MOVEID3: EntityFeature
ENTITY_FEATURE__MOVEPP0: EntityFeature
ENTITY_FEATURE__MOVEPP1: EntityFeature
ENTITY_FEATURE__MOVEPP2: EntityFeature
ENTITY_FEATURE__MOVEPP3: EntityFeature
ENTITY_FEATURE__HAS_STATUS: EntityFeature
ENTITY_FEATURE__BOOST_ATK_VALUE: EntityFeature
ENTITY_FEATURE__BOOST_DEF_VALUE: EntityFeature
ENTITY_FEATURE__BOOST_SPA_VALUE: EntityFeature
ENTITY_FEATURE__BOOST_SPD_VALUE: EntityFeature
ENTITY_FEATURE__BOOST_SPE_VALUE: EntityFeature
ENTITY_FEATURE__BOOST_ACCURACY_VALUE: EntityFeature
ENTITY_FEATURE__BOOST_EVASION_VALUE: EntityFeature
ENTITY_FEATURE__VOLATILES0: EntityFeature
ENTITY_FEATURE__VOLATILES1: EntityFeature
ENTITY_FEATURE__VOLATILES2: EntityFeature
ENTITY_FEATURE__VOLATILES3: EntityFeature
ENTITY_FEATURE__VOLATILES4: EntityFeature
ENTITY_FEATURE__VOLATILES5: EntityFeature
ENTITY_FEATURE__VOLATILES6: EntityFeature
ENTITY_FEATURE__VOLATILES7: EntityFeature
ENTITY_FEATURE__VOLATILES8: EntityFeature
ENTITY_FEATURE__SIDE: EntityFeature
ENTITY_FEATURE__TYPECHANGE0: EntityFeature
ENTITY_FEATURE__TYPECHANGE1: EntityFeature
ENTITY_FEATURE__ACTION_ID0: EntityFeature
ENTITY_FEATURE__ACTION_ID1: EntityFeature
ENTITY_FEATURE__ACTION_ID2: EntityFeature
ENTITY_FEATURE__ACTION_ID3: EntityFeature
ENTITY_FEATURE__NUM_MOVES: EntityFeature
ENTITY_FEATURE__IS_PUBLIC: EntityFeature
ENTITY_FEATURE__LAST_MOVE: EntityFeature
MOVESET_ACTION_TYPE_ENUM___UNSPECIFIED: MovesetActionTypeEnum
MOVESET_ACTION_TYPE_ENUM__MOVE: MovesetActionTypeEnum
MOVESET_ACTION_TYPE_ENUM__SWITCH: MovesetActionTypeEnum
MOVESET_HAS_PP_ENUM___UNSPECIFIED: MovesetHasPPEnum
MOVESET_HAS_PP_ENUM__YES: MovesetHasPPEnum
MOVESET_HAS_PP_ENUM__NO: MovesetHasPPEnum
MOVESET_FEATURE___UNSPECIFIED: MovesetFeature
MOVESET_FEATURE__ACTION_ID: MovesetFeature
MOVESET_FEATURE__PP_RATIO: MovesetFeature
MOVESET_FEATURE__MOVE_ID: MovesetFeature
MOVESET_FEATURE__SPECIES_ID: MovesetFeature
MOVESET_FEATURE__PP: MovesetFeature
MOVESET_FEATURE__MAXPP: MovesetFeature
MOVESET_FEATURE__HAS_PP: MovesetFeature
MOVESET_FEATURE__ACTION_TYPE: MovesetFeature
ACTIONS_FEATURE___UNSPECIFIED: ActionsFeature
ACTIONS_FEATURE__MOVE_ID: ActionsFeature
ACTIONS_FEATURE__ACTION_INDEX: ActionsFeature
RELATIVE_EDGE_FEATURE___UNSPECIFIED: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__MAJOR_ARG: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__MINOR_ARG0: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__MINOR_ARG1: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__MINOR_ARG2: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__MINOR_ARG3: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__ACTION_TOKEN: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__ITEM_TOKEN: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__ABILITY_TOKEN: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__NUM_FROM_TYPES: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN0: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN1: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN2: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN3: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_TYPE_TOKEN4: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__NUM_FROM_SOURCES: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN0: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN1: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN2: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN3: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__FROM_SOURCE_TOKEN4: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__DAMAGE_RATIO: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__HEAL_RATIO: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__EFFECT_TOKEN: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__BOOST_ATK_VALUE: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__BOOST_DEF_VALUE: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__BOOST_SPA_VALUE: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__BOOST_SPD_VALUE: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__BOOST_SPE_VALUE: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__BOOST_ACCURACY_VALUE: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__BOOST_EVASION_VALUE: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__STATUS_TOKEN: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__SIDECONDITIONS0: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__SIDECONDITIONS1: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__TOXIC_SPIKES: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__SPIKES: RelativeEdgeFeature
RELATIVE_EDGE_FEATURE__MOVE_TOKEN: RelativeEdgeFeature
ABSOLUTE_EDGE_FEATURE___UNSPECIFIED: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__TURN_ORDER_VALUE: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__TYPE_TOKEN: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__WEATHER_ID: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__WEATHER_MIN_DURATION: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__WEATHER_MAX_DURATION: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__TERRAIN_ID: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__TERRAIN_MIN_DURATION: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__TERRAIN_MAX_DURATION: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__PSEUDOWEATHER_ID: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__PSEUDOWEATHER_MIN_DURATION: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__PSEUDOWEATHER_MAX_DURATION: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__REQUEST_COUNT: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__VALID: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__INDEX: AbsoluteEdgeFeature
ABSOLUTE_EDGE_FEATURE__TURN_VALUE: AbsoluteEdgeFeature
