# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemon.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpokemon.proto\x12\x07pokemon\x1a\x0b\x65nums.proto\"\xd5\x03\n\x07Pokemon\x12#\n\x07species\x18\x01 \x01(\x0e\x32\x12.enums.SpeciesEnum\x12\x1e\n\x04item\x18\x02 \x01(\x0e\x32\x10.enums.ItemsEnum\x12%\n\x07\x61\x62ility\x18\x03 \x01(\x0e\x32\x14.enums.AbilitiesEnum\x12!\n\x07move1Id\x18\x04 \x01(\x0e\x32\x10.enums.MovesEnum\x12!\n\x07move2Id\x18\x05 \x01(\x0e\x32\x10.enums.MovesEnum\x12!\n\x07move3Id\x18\x06 \x01(\x0e\x32\x10.enums.MovesEnum\x12!\n\x07move4Id\x18\x07 \x01(\x0e\x32\x10.enums.MovesEnum\x12\x0f\n\x07pp1Used\x18\x08 \x01(\x05\x12\x0f\n\x07pp2Used\x18\t \x01(\x05\x12\x0f\n\x07pp3Used\x18\n \x01(\x05\x12\x0f\n\x07pp4Used\x18\x0b \x01(\x05\x12\x0f\n\x07hpRatio\x18\x0c \x01(\x02\x12\x0e\n\x06\x61\x63tive\x18\r \x01(\x08\x12\x0f\n\x07\x66\x61inted\x18\x0e \x01(\x08\x12\r\n\x05level\x18\x0f \x01(\x05\x12\"\n\x06gender\x18\x10 \x01(\x0e\x32\x12.enums.GendersEnum\x12)\n\nitemEffect\x18\x11 \x01(\x0e\x32\x15.enums.ItemeffectEnumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokemon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POKEMON']._serialized_start=40
  _globals['_POKEMON']._serialized_end=509
# @@protoc_insertion_point(module_scope)
