# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import action_pb2 as action__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x05rlenv\x1a\x0c\x61\x63tion.proto\"\x89\x01\n\rWorkerMessage\x12\x14\n\x0cworker_index\x18\x01 \x01(\x05\x12\x32\n\x0cmessage_type\x18\x02 \x01(\x0e\x32\x1c.rlenv.WorkerMessageTypeEnum\x12\x1d\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\r.rlenv.Action\x12\x0f\n\x07game_id\x18\x04 \x01(\x05*\x8e\x01\n\x15WorkerMessageTypeEnum\x12*\n&WORKER_MESSAGE_TYPE_ENUM___UNSPECIFIED\x10\x00\x12#\n\x1fWORKER_MESSAGE_TYPE_ENUM__START\x10\x01\x12$\n WORKER_MESSAGE_TYPE_ENUM__ACTION\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERMESSAGETYPEENUM']._serialized_start=179
  _globals['_WORKERMESSAGETYPEENUM']._serialized_end=321
  _globals['_WORKERMESSAGE']._serialized_start=39
  _globals['_WORKERMESSAGE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
